# -*- coding: utf-8 -*-

import re
from pathlib import Path

# 使用前，将本地化文件放在该.py文件的同一目录下！
loc_file_input = "tf_schinese.txt"
loc_file_output = "tf_schinese_output.txt"

loc_dict = {'ArmoryFilter_MiscItems': '饰品', 'Attrib_HealthDrainMedic': '装备时每秒生命值自回复量 %s1',
            'Attrib_OverhealUberchargeRate_Negative': '超量治疗时，医疗枪的 UberCharge 充能速率 %s1%',
            'ClassTips_5_6_MvM': '升级你的 Ubercharge 来获得更快的充能速率和更长的持续时间',
            'Tip_3_5': '作为士兵，当有医生治疗你时，考虑下适可而止地伤害自己。因为超量治疗时 UberCharge 的充能速率会减慢（准备阶段时除外）。',
            'Tip_4_22': '作为爆破手，当你和医生搭档时，选择安全的时机对自己造成伤害，加快 UberCharge 的充能速度。',
            'Tip_5_4': '作为医生，治疗受伤严重的队友可以更快地补充 UberCharge 。', 'Tip_5_6': '作为医生，在准备阶段时 UberCharge 的充能速率会快很多。',
            'Tip_5_10': '作为医生，最好尽早使用 UberCharge，不然因为被杀而白费全部能量就得不偿失了。',
            'Tip_5_16': '作为医生，使用过载充能锯击中处在原子能饮料效果中的侦察兵依然可以为你补充 UberCharge 能量。',
            'Tip_5_20': '作为医生，用过载充能锯击中一个已伪装的间谍不会为你补充 UberCharge 能量。',
            'Tip_5_25': '作为医生，准确把握时机比什么都重要。在能保证自己的安全时，可以暂时不释放 UberCharge，以便在恰当的时机，使它的作用最大化。',
            'Tip_5_31': '作为医生，过载注射枪会依据你的 Ubercharge 计量多少来增加你的移动速度！如果你需要赶往前线或快速逃跑，就装备过载注射枪吧！',
            'Tip_9_29': '作为工程师，歼灭者 6000 的射线可以削减敌方医生的 UberCharge 能量，以及敌方间谍的隐形能量。',
            'Tip_arena_8': '作为医生，使用维塔锯并不能将 UberCharge 带入到下一局中。',
            'TF_Weapon_FlameThrower_desc': '后续燃烧能降低医疗枪提供的治疗和伤害抗性效果。\\n辅助能力：释放压缩气爆，能击退敌人、反弹飞弹，以及为队友灭火。',
            'TF_ScoutBeanie_Desc': '冲出控制点。', 'TF_ScoutWhoopee_Desc': '这顶帽子在眼光挑剔的年轻人间可是潮流顶配，\n你要是理解不了的话简直就是个呆子',
            'TF_Scout_Towels_Desc': '若你可在阴凉处歇息，又何必在烈日下拼杀？',
            'TF_GRFS_2_Desc': '这个全方位战斗单片眼镜，能够以光速接收从卫星发送的信号，这意味着你可能需要得把速度放慢，信号才追得上你。',
            'TF_PEP_ScoutHat_Desc': '这顶帽子纪念了这样一件事：你把它顶在扫帚上，成功诱骗联邦探员对着它打了整整一小时。与此同时，你背着银行里所有的钱逃走了。而你身上的弹孔与这顶帽子相得益彰，毕竟后来你故技重施时，碰上了更聪明的探员。',
            'TF_BacteriaBlocker_Desc': '人类的脸简直是天然的垃圾场。从亲热时的唾液、修车时的油渍、咀嚼过的牛排再到给国王尝膳时试出来的毒，应有尽有。戴上这个细菌封锁罩，一切会变得更加干净。',
            'TF_Soldier_Viking_Hat_Desc': '老子要狠狠踢你屁股，直到把你踢回到过去，再给我把这顶“维京帽子”带回来。',
            'TF_SoldierSamurai_Desc': '战争俳句吟，\\n爆击火箭携荣誉，\\n杀敌铸忠心。',
            'TF_HonchosHeadgear_Desc': '这顶帽子上写满了刻薄的话。\\n(官方的说法：这顶帽子上没有写着任何东西。)', 'TF_InfernalImpaler': '炼狱穿眼魔',
            'TF_SoldierWinterCoat': '圣诞老人的珍藏外套',
            'TF_Conquistador_Desc': '用这顶绝对正宗的、从十六世纪法国角色扮演者的坟墓堆里挖出来的征服者头盔，唤醒西班牙的历史吧。', 'TF_ShinyBauls': '军用装饰炸弹',
            'TF_ShinyBauls_Desc': '这些闪亮的玻璃装饰球人畜无害，就和士兵原本的手雷一样。', 'TF_Soldier_Robot_Helmet': '锡兵钢盔',
            'TF_SoldiersSlopeScopers_Desc': '这么一副顶级滑雪镜一戴，大伙都知道，以你那马马虎虎的水平可不会上什么初学者坡道，相反，你会把能找到的中级坡道都滑个遍——顺便感谢你，找了那么多好玩的缓坡道。',
            'TF_DoeBoy': '远征大兵盔',
            'TF_jul13_the_caribbean_conqueror_Desc': '“你！别再摇帆了，给我趴下做20个俯卧撑！还有你！那个在瞭望台上的，把望远镜扔掉，再给我脸朝甲板趴下！船上的所有人，都赶紧给我趴下开始做俯卧撑！”',
            'TF_jul13_colonial_clogs_Desc': '我敢肯定这就是乔治·华盛顿本人的鞋子，因为我是从一个英国人的屁股里挖出来的，足足埋了两英尺深！',
            'TF_jul13_gangplank_garment_Desc': '爷的海盗大军可从不干烧杀抢掠的\n事，臭蛆一条！在这艘船上你的任务是巡捕自由派和共产主义者，然后按时睡觉！”',
            'TF_xms2013_soldier_marshal_hat': '愚者牛仔帽', 'TF_xms2013_soldier_marshal_beard': '法警的络腮胡',
            'TF_spr17_flakcatcher': '火力集中背心', 'TF_hwn2020_calamitous_cauldron': '倒霉透顶',
            'TF_Plutonidome_Desc': '众所周知，我们的大脑只开发了10%。这意味着\n，你对你大脑做的任何事，都有90%的概率让你变得更聪明，比如让它漂浮在装满钚元素的罐子里。坦白地说，这至少比你什么都不做更有效。',
            'TF_NoseCandy_Desc': '把它戴在你的呼吸器上面，人们就会以为你是个活在幻想中的妄想症疯子。', 'Planeswalker Goggles': '鹏洛客的风镜',
            'TF_xms2013_scout_drummer_hat': '小兵的高筒军帽', 'TF_Pyro_Hat_1': '火焰兵的小童帽', 'TF_XCOM_Pyro': '451 区',
            'TF_Hatless_Engineer_Desc': '有时你真不需要那么多帽子。', 'TF_EngineerWeldingMask': '热浪',
            'TF_BigCountry_Desc': '把如此帅气的头发藏起来实在是太可惜了。', 'TF_ProfessorHair_Desc': '我觉得我可以很肯定地说没人理解量子力学。子弹力学？那可就不一样了。',
            'TF_MasterMind_Desc': '科学小知识：当人脑暴露于氧气环境中，效率能提升70%。时尚小知识：往人脑上随便粘些电子元器件，炫酷度能提升90%。终于，一个能兼顾两者的物品诞生了。',
            'TF_LastStraw_Desc': '喜欢种庄稼？讨厌大太阳？那就扣上帽子，拎起锄头，再捎上你的猎枪，把那些不长眼的混蛋撵走！',
            'TF_robo_engineer_greaser_Desc': '机械未来史成真啦！假装你是一个脾气暴躁、饱经风霜的探矿机器人，于3047年电池开采热之际，啜饮着纳米威士忌，在老到掉渣的赛博西部酩酊大醉。',
            'TF_pocket_protector_Desc': '孤独是世上最致命的无声杀手，一氧化碳其次。但是挂上这个可爱的纵火狂，屏住你的呼吸，然后你就能专心应对其他猖狂的杀手了，比如说车祸和弗莱迪.克鲁格！',
            'TF_jul13_king_hair_Desc': '这头十加仑的德州风暴发旋，只有硬汉才能收拾得服服帖帖。', 'TF_HeavyHair_Desc': '你的对手会在看到这帅气的墨镜和发型时大吃一惊。',
            'TF_CaponesCapper': '干部的软呢帽', 'TF_HeavyHat2': '户外猛男', 'TF_HeavyHat2_Desc': '劈柴火。喝糖浆。定居加拿大。有这顶帽子就足够了。',
            'TF_MaschinensoldatenHelm_Desc': '俗话说：“不吸取平行世界的前车之鉴，必将重蹈覆辙。”不过，反正你还要再干一次，那何不穿上一套邪恶机器人服装来助长你的气焰呢？',
            'TF_MaschinensoldatenHelm': '机器兵卒头盔',
            'TF_RegimePanzerung_Desc': '俗话说：“不吸取平行世界的前车之鉴，必将重蹈覆辙。”不过，反正你还要再干一次，那何不穿上一套邪恶机器人服装来助长你的气焰呢？',
            'TF_KathmanHairdo_Desc': '这个从史前时代流传下来的蓬巴杜发型，是由埃德蒙.希拉里爵士在珠峰附近首次发现的。他在当时还有另一个发现，那就是他自己拉了一裤子。',
            'TF_robo_heavy_football_helmet': '橄榄球场保卫者',
            'TF_robo_heavy_football_helmet_Desc': '这顶头盔纪念着一场巅峰赛事，当年加拿大机器人橄榄球联赛上的史诗对决——参赛双方分别是“蒙特利尔球手队”与他们来自曼尼托巴的敌手“温尼伯的萨斯喀彻温人队”。不信就找个加拿大人问问呗。市橄榄球运动员之间的史诗对决。不信？随便找个加拿大人问问都知道！',
            'TF_robo_heavy_chief_Desc': '长期以来，科学家们一直好奇美洲原住民草屋和棚屋使用的无缝金属结构到底从何而来。秘诀何在？原来原住民身上满是汽油，能够达到焊接所需的 3100 摄氏度高温。',
            'TF_Demo_Robot_Grenades': '电池挂带',
            'TF_Demo_Robot_Grenades_Desc': '史无前例，现在电池将附送在你所购买的爆破手电池挂带中。原因嘛，呃，因为你买的是电池啊。重新声明一下，这可是“史无前例”的 [除去所有那些你买电池的次数]。',
            'TF_robo_demo_pupil': '高清补丁',
            'TF_robo_demo_pupil_Desc': '内置了各种和眼球有关的电影\\n（包括《大开眼戒》《隔山有眼第二部》以及其他三部眼球片）。\\n好让你的朋友们看到你的脸时能感到更自在一些。',
            'TF_robo_demo_fro_Desc': '70 年代经典电影《Blaxton Hale vs. Black HAL 9000》\\n独一无二的纪念帽。',
            'TF_robo_demo_fro': '零式爆炸头', 'TF_DemoInquisitor': '闹事者的猎巫帽',
            'TF_robo_demo_glengarry_botnet_Desc': '这顶无檐软帽配备了一个卫星绒球，可以实时播报忙碌的苏格兰人的相关新闻（高尔夫比分、威士忌价格，还有《勇敢的心》何时上映）。',
            'TF_jul13_gallant_gael_Desc': '有时候，当你豪饮陶壶里的甲醇谷物酒时，会有点精华滴到地上，而不是你的嘴里。用纯正的苏格兰威士忌餐巾布来接住这些佳酿吧。',
            'TF_fall2013_eod_suit_Desc': '人人都喜欢看着自己的敌人被炸飞。但如果你想靠近点好好观赏这一美妙场景的话，那你也成了受害者。\\n这简直是人生最大的悲剧啊。',
            'TF_short2014_badlands_wanderer': '边疆正义', 'TF_sbox2014_juggernaut_jacket': '震威战衣',
            'TF_Medic_Hat_1_Desc': '一份遗物，在一场场战争中辗转相传。其锋芒所在，定叫敌人心领神会。', 'TF_BlightedBeak': '疫医的鸟嘴面具',
            'TF_MedicGeishaHair_Desc': '绿蛙跃古池\\n莲花于水而绽放\\n医生蓄女发', 'TF_MountainCap_Desc': '部队里的人都管它叫巴伐利亚屠夫',
            'TF_MedicMtGHat': '鹏洛客的头盔', 'TF_MedicMtGHat_Desc': '如果有人问起，那就和他们说这对长牙就是你当兽医的资本。',
            'TF_MedicPocketSquare_Desc': '有时候我们会在这些描述里放一些玩笑话。但不开玩笑地说：这一身看起来很不错。非常有型。',
            'TF_MedicStethoscope_Desc': '在你宣布病人死亡的时候，让你看起来像是知道自己是干什么的。',
            'TF_MedicGasMask_Desc': '虽然只是在进行思想实验，但是医生还是戴上了防毒面具，然后从实验室里释放出无毒气体并开始尖叫：“天哪，这些毒气泄漏啦！”，并以此观察其他人的临场反应，不过到目前为止，实验仍无结论。虽然还是有几个人死掉了。这实在是太有意思了。',
            'TF_Medic_Hat_1': '普鲁士尖顶盔',
            'TF_robo_medic_grimm_hatte_Desc': '不论你是在参与临终典礼的 17 世纪的瘟疫医生、使出“墓碑钉头”终结技的职业摔跤手，还是在瘟疫主题家庭餐馆里端出一盘盘的裹培根墨西哥辣椒酿的服务员，这顶帽子都能显得你非常称职。',
            'TF_WeatherMaster_Desc': '当你声称戴上这顶粘着泡沫云朵和闪电卡纸的头盔，就能获得操控气象的自然伟力时，人们管你叫神经病！现在就让他们见识一下！让所有人都好好见识一下！姆呜哈哈哈哈！（其实这顶帽子并不会给你任何力量）',
            'TF_enlightened_mann_style0': '难以形容的浮夸', 'TF_jul13_montys_menace': '红男爵的船形帽',
            'TF_jul13_montys_menace_Desc': '“你是飞行员吗？我看不出来，因为你的帽子伪装得太好了。”（描述翻译自德语）', 'TF_jul13_uncivil_servant': '奢华礼服',
            'TF_jul13_uncivil_servant_Desc': '“花花公子往往金玉其外败絮其中！而你只是四肢发达头脑简单，所以穿回你该穿的衣服！”（描述翻译自德语）',
            'TF_jul13_emergency_supplies': '感觉良好套装',
            'TF_jul13_emergency_supplies_Desc': '“你们好，战士们！你们快死了。快把药拿上。”（描述翻译自德语）',
            'TF_jul13_class_act_Desc': '“你头皮上的毛发实在太吸引人了。现在我们该来一段恋爱关系了吧。”（描述翻译自德语）',
            'TF_jul13_positive_pressure_veil': '危险品防护面罩',
            'TF_jul13_positive_pressure_veil_Desc': '“呼吸总能令我身心愉悦，但空气时有恶臭弥漫。现在我可以笑对空气了。谢谢你，面罩兄。”（描述翻译自德语）',
            'TF_jul13_madmans_mop_Desc': '“我的笑不是来自我的喜悦！我生来就是魔鬼！我觉得这样子挺好的！”（描述翻译自德语）',
            'TF_jul13_heavy_defender_Desc': '“你的钢铁护甲非常坚固。你的胸脯脏器非常安心。”（描述翻译自德语）', 'TF_jul13_bro_plate': '护额钢盔',
            'TF_jul13_bro_plate_Desc': '“虽然你的脑袋里长着一副头骨，但这还不够！于是这顶帽子应运而生，现在你的脑袋外也有一副头骨了。”（描述翻译自德语）',
            'TF_jul13_secret_state_surgeon': '星级医生', 'TF_xms2013_medic_hood': '修女兜帽',
            'TF_jul13_secret_state_surgeon_Desc': '“你并不重要，但我却不一样。我这可是一顶用来保密的帽子。”（描述翻译自德语）',
            'TF_short2014_medic_messenger_bag': '装药的男式挎包',
            'TF_Sniper_Hat_1_Desc': '死鳄鱼的牙，随便哪个老糊涂都拔得了。能把活鳄鱼的牙给拔出来的，那才叫真汉子。',
            'TF_Sniper_Jarate_Headband_Desc': '只有真正的瓶手道大师，才有资格戴上这条在严酷训练中被染黄的白色头巾。',
            'TF_Sniper_Straw_Hat_Desc': '在见谁杀谁的路途中，记得戴上一顶彰显礼貌与效率的帽子。', 'TF_SniperPithHelmet': '射手的木髓遮阳帽',
            'TF_VillainsVeil_Style0': '职业枪手', 'TF_VillainsVeil_Style1': '行刺高手', 'TF_VillainsVeil_Style2': '资深杀手',
            'TF_DotaSniper_Hat': '狙击手的狙击眼镜', 'TF_Hwn_SniperHat': '神圣猎人之帽', 'TF_TouchingStory': '荒原文学家',
            'TF_TouchingStory_Desc': '格子衬衫。烟斗云雾。单拎出来看，这两者都会显得你像个白痴。但把它们放在一起时，你就会变得和安伯托.艾柯一样既聪明又时髦！',
            'TF_Awes_Sniper_Desc': '在这地界，你才是话事的主儿，这不得戴顶镶金星的大牛仔帽才衬得上这份威风。权势有多大，帽子就有多大——眼下这片地盘可都归你管着呢。不瞒你说，要没这顶帽子压阵，还有谁能把你当回事儿呢。',
            'TF_TW_Sniper_Hat': '狙击手的高筒军帽', 'TF_TW_Sniper_Hat_Desc': '这顶帽子非常适合那种平时喜欢藏匿于阴影中，但又会突然从暗处冒出来然后带领游行队伍的狙击手。',
            'TF_SirHootsalot_desc': '如果猫头鹰当真那么聪明，这家伙怎会让你把它粘在肩膀上？这种事细想来，你俩都不像什么超级天才。', 'TF_StrawBoat': '悉尼平顶草帽',
            'TF_SteelSongbird_Desc': '狙击手老窝里鸦雀无声。为何不静下心来，好好欣赏这只胆小又哑巴的小鸟在受惊失禁时，响起的那一段段余音绕梁的螺栓交响乐呢？',
            'TF_fall2013_brimfull_of_bullets': '大镖客的镶弹帽', 'TF_fall2013_brimfull_of_bullets_style2': '小人',
            'TF_DesertMarauder': '荒漠大盗', 'TF_OlSnaggletooth': '老鳄鱼龅牙', 'TF_fall2013_lil_snaggletooth': '小鳄鱼龅牙',
            'TF_fall2013_lil_snaggletooth_Desc': '‘我长大后也要成为一顶帽子。’——小鳄鱼龅牙', 'TF_hw2013_leather_face': '满口烂牙的斯泰森帽',
            'TF_hw2013_sir_shootsalot': '夜袭者爵士', 'TF_xms2013_sniper_beard': '蓄半年的大胡子',
            'TF_sbox2014_archers_groundings': '弓箭手之靴', 'TF_sept2014_hillbilly_speedbump': '乡巴佬减速带',
            'TF_sept2014_poachers_safari_jacket': '偷猎者的游猎夹克', 'TF_sf14_marsupial_man': '袋鼠怪人',
            'TF_dec2014_hunter_ushanka': '职业杀手的护耳帽', 'TF_dec2014_wally_pocket': '口袋袋鼠',
            'TF_Spy_Camera_Beard_Desc': '你不会介意我用这胡子来翻看这份绝密文件吧？',
            'TF_SpyNobleHair_Desc': '人们都说正义是盲目的。但没人会跟你说，正义也是无形的，而且人们对正义的兴趣还不如对谋杀来的多。',
            'TF_SpyBeret_Desc': '因为真正的谍报行动也是一种艺术形式。', 'TF_Spy_Derby_Hat_Desc': '专为那些想要头顶显高，但又保持圆润线条的人设计。',
            'TF_TheFamiliarFez': '眼熟的非斯帽', 'TF_PartyPhantom': '舞会魅影', 'TF_SpyOniMask_Desc': '嗜烟法国人\\n潜于影伺机而动\\n面具很吓人',
            'TF_Charmers_Chapeau': '魅影骑士帽', 'TF_JanissaryHat': '耶尼切里头冠',
            'TF_CosaNostraCap_Desc': '如果外表也能杀人，那么这顶讲究的帽子兄弟必会让你的脑袋也变成谋杀帮凶。',
            'TF_MadeMan_Desc': '体面的绅士们总要随身带朵花，以便随手掷在对手的墓碑上。', 'TF_SpyHat1': '冒牌的圆顶礼帽',
            'TF_robo_spy_bootleg_billycock': '盗版的铁皮礼帽', 'TF_Hwn_SpyMisc1': '隐形怪人的目镜', 'TF_Hwn_SpyMisc2': '隐形怪人的特制围巾',
            'TF_Hwn_SpyHat': '隐形怪人的面容', 'TF_HA_Spy': '忍者面罩', 'TF_SpyOpenJacket': '商务休闲装', 'TF_SpySpats': '鬼鬼祟祟潜行鞋罩',
            'TF_SpySpats_Desc': '说的没错，你需要一副鞋来帮助你在暗中藏身。可一套上了这副精致的小牛皮鞋罩，你就巴不得全世界都来多看你两眼。', 'TF_DashinHashshashin': '无影刺客',
            'TF_DashinHashshashin_Desc': '当你准备深入敌后时，光伪装几下是不够的！要用兜帽遮住面罩，再裹上一条围巾。这时候你就能大胆地向全世界宣布，你们根本察觉不到我！',
            'TF_Spy_Robot_Fedora': '隐秘硬钢帽',
            'TF_Spy_Robot_Fedora_Desc': '对背刺失去了兴趣？潜入作战对你来说已经是小事一桩？那么试试将这顶15磅重的钢铁帽子戴在头上吧！在你弯腰给步哨枪放置工兵时，享受脖子受到千斤压迫的重量级挑战吧！这可是足以压断颈椎的绝佳消遣哦！',
            'TF_SpyCardHat_Desc': '为什么我们会无耻到直接从帽子上掏一张牌来作弊？也许你该问：为什么我们的刀子…会在你的肚子里？！可能也想问：离这最近的医院在哪？！还有：失血会有别人说的那么严重吗？！',
            'TF_TW_Spy_Coat_Desc': '这件衣服可极大提升你的形象，让人一看便知你是间谍中的佼佼者，甚至别的衣服都没必要穿了。下次你就只穿这一件，在盛大晚宴上近乎裸体地盛装出席，尽情吸引人们的目光吧。看看他们多么羡慕嫉妒恨。那个报警的家伙是咋回事？他这是嫉妒了吗？那还用说么。',
            'TF_Dishonored_Mask_Desc': '这骗子们专门用这个面具来施展书上的一个古老骗术：让所有人都以为你是一个倒霉透顶、颜面无存而且还刚拔完牙的机器人，这样就可以让他们借给你一笔钱！如果骗术被识破了，还可以用眼孔里配备的枪来直接抢劫他们！',
            'TF_DapperDisguise_Desc': '化身一名潇洒绅士，尽情享受高颜值带来的潜藏便利：高薪工作！香艳邂逅！还有橄榄园餐厅的免费面包棍！尽你所能地多吃多占吧，因为面具终将腐烂脱落，而你会变得比以前更加丑陋。',
            'TF_robo_spy_backbiter_billycock': '贱金属小礼帽', 'TF_robo_spy_camera_beard': '百万像素级摄像胡子',
            'TF_jul13_double_clue_Desc': '“调查员，把门锁上！凶手就在这屋子里！”[停顿]“凶手就是我！”[连捅数刀的声音]',
            'TF_short2014_invisible_ishikawa': '盗贼短袍', 'TF_short2014_spy_ascot_vest': '潮流杀手',
            'TF_hw2013_brain__bowler': '高压式圆顶帽', 'TF_hw2013_harmburg': '贩糖人的帽子', 'TF_fall2013_superthief': '坏堡神偷',
            'TF_ToweringPillar_Hat': '层叠高耸的群帽之塔',
            'TF_ToweringPillar_Hat_Desc': '啊哈哈！你那粗鄙无礼的样子像极了一个身无分文的爱尔兰人。休得玷污我这群帽之塔的威严。',
            'TF_robo_all_towering_pillar': '层叠高耸的钛金帽之塔',
            'TF_robo_all_towering_pillar_Desc': '阿西莫夫的机器人三定律说：1. 机器人不得伤害人类，2. 机器人必须服从人类的命令，3. 这帽真气派。',
            'TF_ModestPile_Hat': '低调内敛的一帽之柱', 'TF_ModestPile_Hat_Desc': '毕竟绅士岂能无帽。',
            'TF_robo_all_modest_pile': '低调内敛的废铁帽之柱', 'TF_robo_all_modest_pile_Desc': '这柱谦卑之帽向世界诉说：生命中有些事情比钱更重要。比如，没钱。',
            'TF_NobleAmassment_Hat': '荣华富贵的帽中之帽', 'TF_NobleAmassment_Hat_Desc': '帽上加帽尽显非凡，这位绅士深以为然。',
            'TF_robo_all_noble_amassment': '荣华富贵的镍铁帽中帽',
            'TF_robo_all_noble_amassment_Desc': '有些帽塔起于寒微，一帽接一帽地向上攀登。而你眼前这一柱则属于另一类，人家不过是有个富贵的爹，在惠普公司担任首席业务发展官。',
            'TF_ToweringPillarOfSummerShades': '层叠高耸的夏日太阳镜', 'TF_dec20_pillar_of_beanies': '层叠高耸的针织帽',
            'TF_dec20_pile_of_presents': '层叠高耸的礼物盒', 'TF_hwn2021_towering_patch': '层叠高耸的南瓜壳',
            'TF_FoundryAchievementHat': '蒸腾沸顶之帽',
            'TF_FoundryAchievementHat_Desc': '你们在 cp_foundry 战斗时从来都不带歇的，如今就拿这件汽笛做个凭证吧。它本用来提醒大家，什么时候该到点收工，可你们就是要干个没完没了！',
            'TF_DoomsdayAchievementHat': '静候佳音之帽',
            'TF_DoomsdayAchievementHat_Desc': '这顶神采飞扬的的冲天礼帽，全兵种皆可使用。帽中内置的一枚火箭，每逢发射纪念日皆有可能轰然炸响，只为纪念那场人类与猿类，为征服苍穹而同舟共济的壮举。',
            'TF_FancySpellbook_Desc': '\\n这是一本精美的魔咒书，塞满了由你收集的各种书页。可魔法永远不嫌多…',
            'TF_UnfilledSpellbook_Desc': '\\n这是一本精美的魔咒书，可书页还差着呢！一旦凑齐足够的页数，你就可以装备它来施放魔咒。', 'TF_Spellbook_Basic': '魔咒杂志',
            'TF_Spellbook_Basic_Desc': '一份《术士季刊》的复刻本。\\n从壁橱底下翻出来的，里头那点魔法刚好可堪一用。\\n\\n装备后可拾取与释放魔咒。',
            'TF_SpellbookPage_Desc': '这张魔咒书页依旧存有些许魔力。\\n\\n手头有本魔咒书的话，打开背包将它塞进去吧。',
            'TF_Item_SecretDiary_FireProof_Desc': '看上去有点死灰复燃的势头，除此之外都还将就。造出这玩意儿的材料，肯定是古文明用来合成太空人的。',
            'TF_Summer_Shades_Desc': '这副墨镜还真有名。', 'TF_Halloween_Hat': '阴森隐然的万圣节面具',
            'TF_Halloween_Hat_Desc': '棕色的纸袋儿，从未如此阴森隐然。',
            'TF_HonestyHalo_Desc': '有些人为获取帽子不择手段，但你在头部装潢之业上一贯光明磊落。正因如此，你应得嘉奖。',
            'TF_Soldier_Medal_Web_Sleuth_Desc': '授予少数忠于职守的英勇士兵，他们为了站岗，一个个不眠不休，不吃不喝，连社交生活都不要了。',
            'TF_WikiCap_Desc': '授予 TF2 官方维基的杰出贡献者\\nhttps://wiki.teamfortress.com/',
            'TF_TTG_Badge_Desc': '同时亦允许杀害、折断、粉碎、啃咬。但主要是允许致人残废。',
            'TF_HelpedNewUserHat_Desc': '赠予你老师的礼物，象征着觉悟与洞察，捎带着曲别针与橡皮圈',
            'TF_PotatoHat_Desc': '采用农产品供能的个人照明及头部保护设备。\\n\\n在光圈设施以外不得使用。', 'TF_SpiralSallet': '螺旋骑士盔',
            'TF_KillerExclusive_Desc': '取敌首，夺头条，杀人亦诛心。', 'TF_Football_Scarf_Desc': '将一抹色彩鲜明的忠诚系于脖上。',
            'TF_CrimeCraftHelmet': '栓动闪击盔',
            'TF_CrimeCraftHelmet_Desc': '蹲下来听我说啊，小伙子们。不管什么样的头盔，得戴在脑门上，才能保护脑袋——可要是没戴呢？栓动闪击盔解决了这一难题，它有三根1.25英寸的粗牙螺纹电镀螺栓，牢牢钉死在你的头骨上。记得挑个最喜欢的颜色，毕竟你可得戴着它入土呢。',
            'TF_SD_Glasses': '大鼻笑咖',
            'TF_SD_Glasses_Desc': '世人皆知，欢笑是最佳的良药。但你是否知道，欢笑也是最好的伪装？不知道？还好你不是在中国黑社会里卧底的条子。哦不，你还真是。这下你死定了。自己看吧，菜鸟，这副眼镜有多搞笑。',
            'TF_Awes_Medal_Desc': '这枚徽章代表着另一个佣兵组织对你的承认。但也仅此而已，明白吗？并不是说人家真的喜欢你之类的。他们几周前给你发了佣兵派对邀请函，也不代表就真的希望你去露面。他们可是冷血杀手，懂了吗？\n 哦对了，到时候派对上可有菠菜酱哦。',
            'TF_XCOM_Pin_Desc': '这枚徽章向世人傲然宣告：外星人真实可能存在的可能性，你至少算是马马虎虎意识到了一点。 你去过几场外星人研究大会，曾经若有所思地遥望着天空，\n还把《天兆》反复看了好几回。 如果地外生命有朝一日当真降临，你便可以堂而皇之地向大家展示这件徽章，表示这种事发生的可能性早就让你乐在其中了。',
            'TF_COH2_Badge_Desc': '这个徽章证明你是英雄连的一员，当然这并不代表你是个英雄。只不过有几个相识的英雄人物，偶尔也捎着你混混日子而已。',
            'TF_CronesDome_Desc': '数百年来，巫婆的种种特权，尽都给女人享受完了（制不完的魔药，长不完的疣，还能给人活活烧一回），而男人却只能靠边站。不能再这样下去了！戴上这顶巫婆尖帽，冲破桎梏，将那无形的职场壁垒，一击粉碎。',
            'TF_BooBalloon_Desc': '这些可爱（但也可怕！）的气球，是用货真价实的幽灵脸蛋充气制成的。趁早下单吧！等到那帮自以为是的幽灵保护人士听说这买卖，非得叫它关停不可。',
            'TF_UnknownMonkeynaut_Desc': '让亲历曼恩公司首场宇航猴惨剧的受害者之魂，在你的肩膀上安家落户！ 和其它曼恩公司酿成的宇航猴惨剧大有不同，“香蕉弹弓行动”连宇宙飞船都没准备过。',
            'TF_ScribHat_Desc': '把这顶可染色的全兵种斗鸡头冠套上，让场上的弱鸡都知道，你才是公鸡中的战斗机。',
            'TF_HM_DisguiseHat_Desc': '戴上这副太阳眼镜，再配上一顶皮帽，用这套经典装扮隐姓埋名吧，就这样混进“熊娃娃”角色模仿会，简直完美！',
            'TF_Clacker2012_Desc': '这块纪念款的场记板，曾属于货真价实的电影导演，就用它来驾驭好莱坞那引人入胜的黑魔法吧！这下，你可以亲自对瑞安.诺兹发号施令了！',
            'TF_Tuxxy_Desc': '身着第二届年度萨氏金像奖的颁奖服装，闪耀登场吧。敌人的鲜血，将为你的盛装出席铺就一条红毯。', 'TF_ToughStuffMuffs': '严严实实护耳帽',
            'TF_ToughStuffMuffs_Desc': '耳部冻伤将导致血液循环不畅，进而引发组织坏死、坏疽、以及感染。没人想看见你那双耳溃烂的样子。都给冻得如此不堪入目了，还不快用这副时尚的耳罩给它扣上！',
            'TF_Wreath_2012_Desc': '将带刺的叶子和有毒的浆果钉在胸口，堪称‘开心过大节’的无上表达。',
            'TF_Pet_Balloonicorn_Desc': '哎哟喂！那位可是气球独角兽？火焰兵幻境的一把手？瞎说啥呢，不就一充了气的独角兽而已。人家是市政监察员啊。私下跟你说吧，整个市政厅上下，全都在笑话他。那个管下水道的加里.布罗曼，也是个充气的，跟他老婆有一腿呢。所以嘛，他最近老是喝得烂醉，臭脾气也是一点就着，在你肩上晃悠的时候，可万万不可提这茬啊。',
            'TF_Pet_Reindoonicorn_Desc': '众驯鹿间知名度排行第十？走着瞧吧！自打那只鼻尖儿上长了个荧光疙瘩的变种怪胎出了风头，气球驯鹿独角兽就这么坐上了冷板凳，的确是跌入了鹿生低谷。但几十年来，他在各大教养所间摸爬滚打，足足锻炼了一肚子的胆量和志气，誓要重返巅峰不可！最近还老有人瞧见，他跟九个全副武装的精神病在一块儿厮混。这么一合计，此鹿那叫一个势在必得，铁定得看好啊。',
            'TF_WilsonWeave': '威尔逊假发', 'TF_AllFather': '众神之父的胡子', 'TF_jul13_macho_mann_glasses_Desc': '有时还真得全村一起上，乡亲们。',
            'TF_PocketMedic_Desc': '随身携带会治疗的小家伙。', 'TF_dec15_gift_bringer': '赠礼之人',
            'TF_GRFS_3_Desc': '这条战场感知面罩由纳米纤维缝合而成，可以从维基百科下载战场资料，直接传输到你的面前，所以你再也不会错失这些信息了。',
            'TF_SD_Tattoos_Desc': '纹上你的霸气刺青，给那些中国黑社会瞧瞧谁才是大佬，还不真去干那些犯罪勾当！注意：千万别真给他们看到了。', 'TF_SpookySleeves': '骷髅长袖衫',
            'TF_SpookySleeves_Desc': '趁着格伦.但泽还没发现它们，赶紧下单！否则他会把库存一扫而空！说真的，骷髅长袖衫有货的世界，和格伦.但泽存在的世界，你只能选择其一，两者不可兼得！赶紧的！他正上谷歌疯狂搜索“骷髅长袖衫”呢！',
            'TF_sbox2014_toowoomba_tunic': '图文巴短袍', 'TF_enlightened_mann': '扑粉行家',
            'TF_enlightened_mann_Desc': '这顶假发在任何旅行急救包中都不可或缺，倘若迪士尼总统大厅的蜡像都活了过来，它能助你逃出升天。我们还附赠了一顶三角帽，以免活过来的不是总统而是加勒比海盗。',
            'TF_hw2013_ethereal_hood': '空灵兜帽', 'TF_UnarmedCombat_Desc': '多谢间谍助我一臂之力...', 'TF_Weapon_Bat': '球棒',
            'TF_Unique_TribalmanKukri': '部落砍刀',
            'TF_CSGO_AWP_Desc': '这把充满争议而不失优雅的栓动式狙击步枪在无数国家遭到禁用，理由只有一个：它会同时从生理和心理上对人们造成严重的伤害。', 'TF_SolemnVow': '神圣誓言像',
            'TF_SolemnVow_Desc': '“不得害人。”——《希波克拉底誓言》', 'TF_Unique_BattleAxe': '苏格兰碎颅斧', 'TF_Weapon_HotHand': '火热手感',
            'TF_Weapon_HotHand_Desc': '它会告诉你的对手，以及所有正在看着屏幕右上角的人一件事：某张幸运的脸蛋被你一巴掌扇成了蠢蛋。',
            'TF_Gunbai_Desc': '石海阴风起\\n侦察举扇夺命来\\n你已被标记', 'TF_SoldierSashimono_Desc': '疾风助群行\\n伤敌愈深愈生力\\n血战即血怒',
            'TF_SoldierKatana_Desc': '士兵对爆破\\n双刃交锋决生死\\n一击定乾坤', 'TF_Kunai_Desc': '初时气血微\\n刃下诛敌夺精元\\n尽纳己身归',
            'TF_TheHolyMackerel': '尚方宝鲭', 'TF_TheHolyMackerel_Desc': '挨咸鱼一顿打，脸都要丢光了。',
            'TF_ConscientiousObjector': '和平示威牌',
            'TF_BallBuster_Desc': '这些节日小装饰的做工真是精美，连你的敌人都想凑近过来观赏。何不成全他们——把这些易碎的玻璃球以90英里的时速砸进他们眼睛里？',
            'TF_Rainblower_Desc': '当你向朋友们（敌人们）喷洒闪耀的彩虹（吞噬一切的火焰）时，他们会发出银铃般的欢笑（血肉焦裂的爆响）。（启用火焰兵幻境）',
            'TF_Phlogistinator_Desc': '这件革命性的装置，能够唤醒所有可燃生物体内的火焰元素——“燃素”，也就是说，让所有的可燃生物都可燃。',
            'TF_Weapon_DragonsFury_Desc': '威力强大的单发火焰喷射器，连续命中敌人可以加快攻击速度，并造成额外伤害。',
            'TF_ManMelter_Desc': '此武器在不手持时也会自动装弹。\\n\\n这件装置的存在是对传统科学共识的公然侮辱——人体内的分子不再是“井然有序”地排列，而可散落在一平方英里内。',
            'TF_GasPasser_Desc': '制造一团触目惊心的气体云雾，其中的可燃物质会附着在接触雾气的敌人身上，使敌人在受到伤害后会持续燃烧（对火焰兵同样有效！）',
            'TF_Lollichop_Desc': '用这个超大的美味波板糖（冰冷的钢铁）来填满（劈开）你的伙伴的肚子（颅骨）吧。（启用火焰兵幻境）',
            'TF_ThirdDegree_Desc': '这把妙不可言的伐“物”利器堪称全球伐木工、拓荒边民和原子切割手的福音，其奥妙在于——劈开物体的同时，还能将每个分子燃烧至渣。',
            'TF_Weapon_Cannon_desc': '双重轰击！炮弹在击中目标后，爆炸对此目标造成迷你爆击', 'TF_Weapon_PipebombLauncher_desc': '辅助攻击：引爆全部黏性炸弹',
            'TF_SplendidScreen_desc': '辅助攻击：移除负面效果，向敌人发起冲锋。\\n冲锋撞击敌人时，获得一次近战武器爆击。',
            'TF_Unique_Achievement_Shield_Desc': '辅助攻击：移除负面效果，向敌人发起冲锋。\\n远距离冲锋撞击敌人时，获得一次近战武器爆击。',
            'TF_TideTurner_Desc': '辅助攻击：移除负面效果，向敌人发起冲锋。\\n远距离冲锋撞击敌人时，获得一次近战武器迷你爆击。',
            'TF_ScottishHandshake_Desc': '你的敌人会以为你在求和，直到手被割出个血口子的那一刻，他们才恍然大悟！而诀窍就在这儿：用碎掉的酒瓶！',
            'TF_HalloweenBoss_Axe_Desc': '其中作祟的暗黑灵魂，和苏格兰长剑里的也没什么两样。',
            'TF_UllapoolCaber_Desc': '一柄苏格兰风情，让人眨眼间面目全非。\\n换头脑清醒的人来早扔出去了…\\n\\n首次敲击会产生爆炸',
            'TF_Robot_Sandvich_Desc': '机器人可不只会喝油。它们还会啃一些外形与人类食物相似的金属制品。你问为什么？既然你这么聪明，那要不你来告诉我为什么？真要这么说的话，吃块铁皮三明治就是要合理得多。你要真这么喜欢油，咋不跟它结个婚，生个娃，然后一塌糊涂地把婚离了，两个人一块承担监护责任啊？',
            'TF_MasculineMittens_Desc': '戴上这双引人发笑的拳套，成为战斗盛宴中的气氛担当吧。',
            'TF_Weapon_Wrench_Desc': '敲击友方建筑可进行升级和修复，同时亦可加快建造速度',
            'TF_SpyCicle_Desc': '对于什么都不缺的人来说，这才是最完美的礼物：一根刺入后背的冰锥。就算你再有钱，商场里也没这货。',
            'TF_HM_Watch_Desc': '这副间谍腕表乃德国工程学的杰作，以澳元素与钨合金所打造的双色美学，尽显经典风范，专为品味非凡的欧洲刺客而生。每一次隐身，都是一次无形无声的炫富。',
            'TF_Weapon_Ap_Sap_desc': '曼恩公司拿下了一笔划算的交易，从某废弃科研设施的好心女士那里，收购了整整一仓库的电子工兵。它们几乎没怎么用过，还可能有丁点小问题，而且和其它型号有些不同——它具有自主意识，也就是说它会在你想专心干活时，自顾自地滔滔不绝上好几个小时。',
            'TF_TTG_MaxGun_Desc': '半隐蔽式武器中的巅峰之作。毫无疑问，你需要这把枪，唯一的问题是：你能把它藏在哪里呢?', 'TF_SpyCicle': '神奇的冰锥',
            'TF_TheShortstop_Desc': '4 发弹匣供弹，每次装填整个弹匣。\\n辅助能力：推开敌人！\\n\\n曼恩公司最新出品\\n采用高姿态中折式原理的防身利器。',
            'Attrib_HypeOnDamage': '击中时：积累跳跃能量', 'TF_SodaPopper_Desc': '当能量积满时，使用辅助能力可开启空中连跳模式。\\n这把武器每次装填整个弹匣。',
            'Attrib_HypeResetsOnJump': '空中跳跃后削减加速能量', 'Attrib_losehypeontakedamage': '受到攻击时削减加速能量',
            'Attrib_BackAttackMinicrits': '近距离射击敌人后背时必定迷你爆击', 'Attrib_CritChance_Disabled': '无随机爆击',
            'TF_Apocofists_Desc': '将你的每根手指都化作末日天启骑士！如此一来，每一只拳套就能降临不止十九位灭世使徒！区区一拳，竟能掌握如此终焉之力！',
            'TF_Unique_Achievement_EnergyDrink_desc': '饮用后获得 8 秒无敌效果，期间无法攻击。\\n期间吸收的伤害，会在效果结束后使你减速。',
            'TF_Unique_EnergyDrink_CritCola_Desc': '生效时：每次攻击均造成迷你爆击，并使自身获得持续 5 秒的死亡标记。',
            'Attrib_ExtinguishReducesCooldown': '为队友灭火 %s1% 冷却时间', 'Attrib_BatLaunchesBalls': '辅助能力：打出一个能使敌人减速的球',
            'Attrib_BleedingDuration': '击中时：使对方持续流血 %s1 秒', 'Attrib_HitSelfOnMiss': '挥空后：打到你自己，笨蛋。',
            'Attrib_CritVsBurning': '对着火的敌人必定爆击', 'Attrib_Minicrit_Vs_Burning_Player': '对着火的敌人必定迷你爆击',
            'Attrib_DmgTaken_From_Fire_ReducedActive': '手持时，火焰伤害抗性 +%s1%', 'TF_RiftFireMace_Desc': '把有刺的那头对着别人。',
            'Attrib_MinicritsBecomeCrits': '在理应造成迷你爆击的情况下，造成爆击',
            'Attrib_MarkForDeath': '击中时：对目标打上死亡标记，使其所受伤害均为迷你爆击，只能对一个敌人生效',
            'Attrib_EffectBarRechargeRateIncreased': '冷却速率 +%s1%',
            'Attrib_AirDashCountIncreased': '手持时，可以进行三段跳。\\n空中近战攻击均为迷你爆击。',
            'Attrib_CannotPickUpIntelligence': '穿戴者无法携带情报箱或手球',
            'TF_Weapon_RocketLauncher_Jump_Desc': '专用于学习火箭跳跃技巧与套路的特殊火箭发射器。\\n此武器的伤害为零！',
            'Attrib_EnergyWeaponChargedShot': '辅助能力：发射能量弹对玩家造成\\n迷你爆击并点燃目标，还可以瘫痪建筑 4 秒',
            'Attrib_AutoFiresFullClip': '按住开火键，装入至多 3 发火箭\\n松开按键后连发释放膛内火箭',
            'Attrib_Projectile_Spread_Angle_Negative': '飞行物随机散布程度 +%s1',
            'Attrib_RocketJumpAttackRateBonus': '爆炸起跳过程中提升攻击速度并削减爆炸范围', 'Attrib_ExtraRocketsOnKill': '杀敌后扩大弹匣容量',
            'TF_Unique_Achievement_SoldierBuff_Desc': '对敌方造成伤害可积累怒气值。\\n怒气满时可激活增益，\\n使你和范围内队友的攻击转为迷你爆击。',
            'TF_TheBattalionsBackup_Desc': '对敌方造成伤害可积累怒气值。\\n怒气满时可激活增益，\\n为你和范围内队友提供减伤保护。\\n降低 50% 步哨伤害 ，\\n免疫爆击的额外伤害，\\n降低 35% 其它所有伤害。',
            'Attrib_DamageForceReduction': '受到伤害产生的击退推力 %s1%', 'Attrib_BootsFallingStomp': '对被踩中的敌人造成 3 倍的摔落伤害。',
            'Attrib_AirBlastVulnerabilityMultipier': '受到气爆产生的击退效果 %s1%', 'Attrib_EnergyWeaponPenetration': '飞行物能穿透敌方目标',
            'Attrib_EnergyWeaponNoDeflect': '飞行物无法被反弹', 'Attrib_BulletsPerShot_Bonus': '单发射击的子弹数 +%s1%',
            'Attrib_SpreadPenaltyScalesCons': '连续射击将导致精准度下降', 'Attrib_IsASword': '此武器具有较大的近战范围\\n取出和收回速度较慢',
            'Attrib_Honorbound': '荣誉之魂：一旦出鞘，除非斩杀敌人，否则收回时将对自身造成 50 点伤害',
            'Attrib_CritWhileAirborne': '火箭跳跃后，未落地前此武器的攻击均为爆击。', 'Attrib_ShovelSpeedBoost': '移动速度随着使用者的受伤程度而增加',
            'Attrib_ShovelDamageBoost': '伤害随着使用者的受伤程度而增加', 'Attrib_HealingFromMedics_Negative': '医生提供的治疗量 %s1%',
            'Attrib_AirblastCost_Increased': '气爆弹药消耗量 +%s1%', 'Attrib_SingleWepDeployBonus': '武器部署速度 +%s1%',
            'Attrib_BurnDamageEarnsRage': '通过造成伤害来积累“呜唔”值。\\n“呜唔”充满时，使用辅助能力：嘲讽以获得数秒的爆击。\\n“呜唔”嘲讽时进入无敌状态。',
            'Attrib_ModFlamethrowerPush': '无法使用压缩气爆', 'Attrib_AirblastDisabled': '无法使用气爆',
            'TF_Weapon_DragonsFury_NeutralDesc': '主要攻击和辅助能力共用同一个压力槽。\\n\\n主要攻击：发射一个高速飞行的火球，并短暂点燃敌人\\n\\n辅助能力：释放一股压缩气流，可以击退敌人、反弹飞行物，并为着火的队友灭火。',
            'TF_Weapon_DragonsFury_PositiveDesc': '对着火的敌人造成 300% 的伤害\\n击中敌人后攻击冷却速率 +50%',
            'TF_Weapon_DragonsFury_NegativeDesc': '使用辅助能力后攻击冷却速率 -50%',
            'Attrib_BlastDamageToSelf_Increased': '自身伤害 +%s1%',
            'TF_Weapon_Flaregun_Detonator_Desc': '辅助能力：引爆信号弹。\\n此武器在不手持时也会自动装弹。',
            'Attrib_ExtinguishRevenge': '辅助能力：为队友灭火可以积累爆击',
            'Attrib_FlaregunPelletsWithKnockback': '信号弹具有击退效果，\\n击中表面后炸开。\\n对于着火的敌人具有更强的击退效果',
            'Attrib_ImpactPushback': '落地时击退敌人（推动力和范围取决于落地速度）', 'Attrib_MeterChargeType3': '油料随时间补充，对敌方造成伤害可以加快补充',
            'Attrib_MeterStartsEmpty': '初始油量为空',
            'Attrib_ConsumesBurning': '对着火敌人造成迷你爆击，并为他们灭火。\\n敌人剩余着火时间越长，伤害越高。\\n击杀着火敌人后获得短暂的移速加成。',
            'Attrib_DmgVsBuilding_Increased': '对建筑物的伤害 +%s1%', 'Attrib_SetDamageType_Ignite': '击中后使目标被火焰吞噬',
            'Attrib_DamageAllConnected': '可以同时伤害所有被医疗枪治疗链所连接的玩家', 'Attrib_CritVsWet': '对湿身的玩家必定爆击',
            'Attrib_SpeedBoostEnemy': '击中敌人时获得移速加成', 'Attrib_ProjectileSpeed_Increased': '炮弹飞行速度 +%s1%',
            'Attrib_ProjectileSpeed_Decreased': '炮弹飞行速度 %s1%', 'Attrib_StickyAirBurstMode': '发射的榴弹在碰到表面后会碎裂',
            'Attrib_ChargeTurnControl': '冲锋状态下的转向控制力 +%s1%',
            'Attrib_Grenade_Launcher_Mortar_Mode': '炮弹的爆炸引信时间为 1 秒，按住开火键可以缩短引信时间',
            'Attrib_Cannonball_Push_Back': '炮弹击中目标会造成击退效果', 'Attrib_Grenade_Not_Explode_On_Impact': '炮弹击中目标时不会立刻引爆',
            'Attrib_MaxPipebombs_Increased': '最大黏性炸弹发射量 +%s1', 'Attrib_StickyDetonateMode': '引爆准星周围和脚下的黏性炸弹',
            'Attrib_StickyArmTimePenalty': '炸弹就绪时间 +%s1 秒', 'Attrib_ChargeTurnControlFull': '冲锋时可自由转向',
            'TF_Weapon_StickyBomb_Jump_Desc': '特殊的无杀伤性黏性炸弹发射器，专用于学习黏弹跳跃的技巧与套路。',
            'Attrib_stickybomb_charge_damage_increase': '蓄力越久伤害越高，至多 +%s1% 伤害',
            'TF_Unique_Achievement_Sword_Desc': '每斩获一个头颅，就能提升\\n一定的移动速度和生命值。',
            'Attrib_AmmoGivesCharge': '可以通过弹药箱补充冲锋能量', 'Attrib_spup_damage_resistance': '生命值低于 50% 且在预热或开火时，所受伤害 %s1%',
            'Attrib_AimingMoveSpeed_Decreased': '预热或开火时移动速度 %s1%', 'Attrib_Spread_Positive': '精准度提高 %s1%',
            'Attrib_Spread_Negative': '精准度降低 %s1%', 'Attrib_MinigunNoSpinSounds': '无声杀手：预热枪管不会发出声音',
            'Attrib_Ring_Of_Fire_While_Aiming': '预热或开火时自身产生一个火圈',
            'Attrib_Uses_Ammo_While_Aiming': '预热或开火时每秒额外消耗 %s1 点弹药',
            'TF_Sandvich_desc': '食用后回复至多 300 点生命值。\\n辅助能力：将三明治分享给队友（相当于中型医疗包）',
            'Attrib_LunchboxAddsMaxHealth': '生命值上限 +50，持续 30 秒',
            'TF_Lunchbox_Chocolate_desc': '食用后可回复至多 100 点生命值。\\n辅助能力：将巧克力分享给队友（相当于小型医疗包）',
            'TF_SpaceChem_Fishcake_Desc': '食用后可回复至多 100 点生命值。\\n辅助能力：将鱼饼分享给队友（相当于小型医疗包）\\n\\nVossler 公司全天然人工鱼肉制品',
            'TF_BuffaloSteak_Desc': '食用后，移动速度提升，攻击均为迷你爆击，\\n并且只能使用近战武器，持续 16 秒。\\n辅助能力：将牛排分享给队友（相当于中型医疗包）\\n\\n谁还要面包呢？',
            'TF_Lunchbox_Banana_desc': '食用后回复部分生命值。\\n辅助能力：将香蕉分享给队友（相当于小型医疗包）',
            'Attrib_CritKillWillGib': '用爆击杀敌会将敌人碎尸万段，惨烈至极！', 'Attrib_DmgFromMelee_Increased': '手持时受到的近战伤害 +%s1%',
            'Attrib_PatientOverheal_Penalty': '装备时超量治疗量上限 %s1%', 'Attrib_SpeedBoostOnHit': '击中后获得一次速度加成',
            'Attrib_CritForcesLaugh': '爆击攻击会强制使敌人大笑', 'Attrib_CritFromBehind': '攻击敌人后背必定爆击',
            'Attrib_ModFlamethrower_BackCrits': '攻击敌人后背必定爆击',
            'Attrib_TickleEnemiesWieldingSameWeapon': '击中后能强制使同样装备此物品的敌人大笑',
            'Attrib_LoseRevengeCritsOnDeath': '死亡后丢失所有的复仇爆击',
            'Attrib_DamageBonusAgainstSentryTarget': '对步哨枪锁定的目标造成的伤害 +%s1%', 'Attrib_NoReload': '无需换弹',
            'Attrib_SubtractVictimCloakOnHit': '击中时：使目标损失至多 %s1% 的隐身能量',
            'Attrib_SubtractVictimMedigunChargeOnHit': '击中时：使目标损失至多 %s1% 的医疗枪能量',
            'Attrib_Building_Telporting_PickUp': '辅助能力：消耗 %s1 金属，远距离搬取目标建筑',
            'Attrib_ArrowHealsBuildings': '发射特殊飞弹，可以修复友方建筑', 'Attrib_MarkedForDeathOnBuildingPickup': '搬运建筑时，对自身产生死亡标记',
            'Attrib_ElectricalAirblast': '辅助能力：消耗 65 金属，发射一个能摧毁飞行物的能量球。',
            'Attrib_GunslingerPunchCombo': '连续三拳命中敌人时，第三拳必定爆击', 'Attrib_WrenchBuildsMiniSentry': '使用迷你型步哨枪',
            'Attrib_ConstructionRate_Increased': '建造加速效果 +%s1%', 'Attrib_ConstructionRate_Decreased': '建造加速效果 -%s1%',
            'Attrib_AltFireTeleportToSpawn': '按下装弹键，可以选择传送回己方出生点或者传送装置出口',
            'Attrib_metal_pickup_decreased': '从弹药箱和补给器获得的金属 -%s1%', 'Attrib_HealthDrain': '装备时每秒 -%s1 生命值',
            'Attrib_HealthRegen': '装备时每秒 +%s1 生命值', 'Attrib_SniperNoHeadshots': '无法爆头',
            'TF_CrusadersCrossbow_desc': '发射特殊箭矢，可以治疗队友，也可以攻击敌人\\n箭矢飞行距离越远，治疗量和伤害量就越高\\n此武器在不手持时也会自动装弹',
            'TF_Overdose_Desc': '手持时，现有的 UberCharge 能量越多，移动速度越快，加速上限为 20%',
            'Attrib_Medigun_CritBoost': 'UberCharge 提供爆击', 'Attrib_UberchargeRate_Positive': 'UberCharge 充能速率 +%s1%',
            'Attrib_UberchargeRate_Negative': 'UberCharge 充能速率 %s1%',
            'Attrib_Medigun_MegaHeal': 'UberCharge 期间治疗速度提高至 300% ，同时免疫减速效果',
            'Attrib_OverhealAmount_Negative': '超量治疗上限降低至 %s1%',
            'TF_Unique_MediGun_QuickFix_Desc': '可以同步模拟治疗目标的爆炸跳跃和盾牌冲锋等动作。',
            'Attrib_Medigun_Resists': '按下装弹键可以切换伤害抗性类型。\\n在治疗时，你和治疗目标会持续获得 10% 当前所选的伤害抗性。',
            'TF_Unique_MediGun_Resist_Desc': 'UberCharge 为医生和治疗目标提供一个持续 2.5 秒的保护罩。根据所选伤害类型，阻挡所受的 75% 的基础伤害和 100% 的爆击额外伤害。',
            'Attrib_AddUber_OnHit_Positive': '击中后获得 %s1% UberCharge 能量', 'Attrib_FireRate_Positive': '攻击速度 +%s1%',
            'Attrib_FireRate_Negative': '攻击速度 -%s1%', 'Attrib_FireRate_Positive_shortdesc': '攻击速度 +%s1%',
            'TF_Unique_BattleSaw_Desc': '根据所获器官数，死后仍能保留一定比例的 UberCharge 能量（每个器官保留 15%）。复活时最多保留 60% 的能量。',
            'Attrib_EnablesAOEHeal': '辅助能力：治疗周围的所有队友', 'Attrib_SeeEnemyHealth': '可以让你看见敌人的生命值',
            'Attrib_SniperCharge_Per_Sec': '充能速率 +%s1%',
            'Attrib_JarateDuration': '开镜击中目标时：对目标施加 2 到 %s1 秒的瓶手道效果。充能时间越久，效果时间越长。\\n人有三急：开镜爆头后只能造成迷你爆击，\\n并会减少瓶手道剩余的冷却时间 1 秒。',
            'Attrib_MultSniperChargePenalty': '初始充能速度减慢 %s1%',
            'TF_BazaarBargain_Desc': '每开镜爆头一次，充能速率即会提升 25% ，最多可提升至 200%。',
            'Attrib_Sniper_FullChargeBonus': '完全充能时：该发伤害 +%s1%', 'Attrib_RageGainOnKill': '杀敌或助攻即可积累“专注”能量',
            'Attrib_SniperRageDisplayOnly': "按下 '装弹' 键以启用专注\\n专注状态：充能速度 +25%，且无法取消开镜",
            'Attrib_SniperCritNoScope': '只能手动充能射击，无论开镜与否均可充能',
            'Attrib_MiniCritBoost_WhenCharged': '辅助能力：充能完毕后使用，即可获得 %s1 秒的迷你爆击',
            'Attrib_MiniCritBoost_ChargeRate': '造成伤害即可填充能量', 'Attrib_Jarate_Description': '敌人在被泼中后所受伤害均为迷你爆击。\\n可用于灭火。',
            'Attrib_DmgTaken_From_Fire_Reduced': '装备时火焰伤害抗性 +%s1%', 'Attrib_AfterburnImmunity': '免疫后续燃烧',
            'Attrib_AimingNoFlinch': '开镜充能完毕时视野不会因其他影响而晃动', 'Attrib_MultDmgBonusWhileHalfDead': '当生命值低于 50% 时，伤害 +%s1%',
            'Attrib_MultDmgPenaltyWhileHalfAlive': '当生命值高于 50% 时，伤害 %s1%', 'Attrib_RevolverUseHitLocations': '爆头可造成爆击',
            'Attrib_Dmg_Crit_Falloff': '爆击伤害受射击距离影响', 'Attrib_DisguiseOnBackstab': '成功背刺人类目标后，自动且迅速地伪装成被杀目标',
            'Attrib_DisguiseConsumesCloak': '使用伪装工具伪装需耗尽全部隐身能量', 'Attrib_Sanguisuge': '成功背刺后，立刻吸收被刺目标的生命值',
            'Attrib_MaxHealth_Positive': '装备时最大生命值 +%s1', 'Attrib_MaxHealth_Negative': '装备时最大生命值 %s1',
            'Attrib_FreezeBackstabVictim': '背刺敌人会使其变成冰雕', 'Attrib_MeltsInFire': '着火会使冰锥融化，需要等待 %s1 秒或捡起弹药箱后才能重新使用',
            'TF_Weapon_Watch_desc': '辅助能力：进入隐形状态。隐形期间无法攻击。触碰敌人会使你略微显形',
            'Attrib_CloakIsMovementBased': '隐身类型：移动敏感型。\\n辅助能力：进入隐形状态。隐形期间无法攻击，并且触碰敌人会使你略微显形。\\n移动速度越快，能量消耗越快。',
            'Attrib_NoCloakWhenCloaked': '隐形时无法通过捡起弹药箱来补充隐形能量', 'Attrib_ReducedCloakFromAmmo': '从弹药箱补充的隐形能量 %s1%',
            'TF_Weapon_Spy_Sapper_desc': '可放置在敌方建筑上，使其失效并且缓慢损失建筑耐久值。放置电子工兵不会解除自身伪装',
            'Attrib_MoveSpeed_Penalty': '装备时移动速度减慢 %s1%', 'Attrib_DmgTaken_From_Fire_Increased': '装备时受到的火焰伤害 +%s1%',
            'Attrib_DmgTaken_From_Crit_Reduced': '装备时爆击伤害抗性 +%s1%',
            'Attrib_DmgTaken_From_Crit_Increased': '装备时受到的爆击伤害 +%s1%',
            'Attrib_DmgTaken_From_Blast_Reduced': '装备时爆炸伤害抗性 +%s1%',
            'Attrib_DmgTaken_From_Blast_Increased': '装备时受到的爆炸伤害 +%s1%',
            'Attrib_DmgTaken_From_Bullets_Reduced': '装备时子弹伤害抗性 +%s1%',
            'Attrib_DmgTaken_From_Bullets_Increased': '装备时受到的子弹伤害 +%s1%', 'Attrib_DmgTaken_Increased': '装备时受到的伤害 +%s1%',
            'Attrib_CaptureValue_Increased': '装备时占领速度 +%s1', 'Attrib_HealthFromHealers_Reduced': '装备时受到治疗者的治疗量 %s1%',
            'Attrib_HealthFromHealers_Increased': '装备时受到治疗者的治疗量 +%s1%', 'Attrib_GestureSpeed_Increase': '装备时嘲讽速度 +%s1%',
            'Attrib_MaxammoPrimary_Increased': '装备时主弹药上限 +%s1%', 'Attrib_MaxammoPrimary_Reduced': '装备时主武器弹药携带量 %s1%',
            'Attrib_MaxammoSecondary_Increased': '装备时副武器弹药上限 +%s1%',
            'Attrib_MaxammoSecondary_Reduced': '装备时副武器弹药上限 %s1%', 'Attrib_MaxammoMetal_Increased': '装备时金属上限 +%s1%',
            'Attrib_MaxammoMetal_Reduced': '装备时金属上限 %s1%', 'Attrib_MoveSpeed_Bonus': '装备时移动速度 +%s1%',
            'Attrib_HealthFromPacks_Increased': '装备时从医疗包获得的生命值 +%s1%',
            'Attrib_HealthFromPacks_Decreased': '装备时从医疗包获得的生命值 %s1%', 'Attrib_AmmoRegen': '装备时每 5 秒 +%s1% 弹药',
            'Attrib_MetalRegen': '装备时每 5 秒 +%s1 金属', 'Attrib_DmgFromSentryReduced': '装备时步哨枪伤害抗性 +%s1%',
            'Attrib_MaxammoGrenades1_Increased': '其它弹药上限 +%s1%',
            'TF_Armory_Item_Attrib_OnWearer': '此物品具有“装备时”属性。只要此物品出现在玩家配置中，即便此物品不是玩家手中的现有武器，此种属性的效果依然会应用于玩家。',
            'TF_Armory_Item_Attrib_OnActive': '此武器仅在手持时具有影响穿戴者的属性。对于大多数“装备时”属性而言，只要物品出现在配置中，该属性就有效。但在这里，这些属性只有当武器拿在玩家手中时才会有效。',
            'Attrib_FlameAmmoPerSec_Increased': '每秒消耗的火焰喷射器弹药 +%s1%',
            'Attrib_FlameAmmoPerSec_Decreased': '每秒消耗的火焰喷射器弹药 %s1%',
            'TF_MadMilk_Desc': '玩家在攻击浑身是牛奶的敌人时\\n可以恢复本次攻击伤害 60% 的生命值。\\n可用于灭火。', 'vintage': '古典', 'collectors': '收藏家',
            'Store_NextStyle': '样式', 'Econ_Style_Desc': '样式： %s1', 'TF_Tag_Category_Rarity': '品级',
            'Rarity_Legendary': '杀手', 'Rarity_Legendary_Weapon': '杀手', 'Rarity_Uncommon': '特约',
            'Rarity_Uncommon_Weapon': '特约', 'TFUI_InvTooltip_ItemFound': '%s1%s2%s3%s4%s5',
            'Item_Found': '%s1 刚刚获得了:: %s2 %s3', 'Item_Crafted': '%s1 已制造:: %s2 %s3',
            'Item_Traded': '%s1 已交易:: %s2 %s3', 'Item_Purchased': '%s1 已购买:: %s2 %s3',
            'Item_FoundInCrate': '%s1 从箱子中发现了:: %s2 %s3', 'Item_Gifted': '%s1 已收到礼物:: %s2 %s3',
            'Item_Earned': '%s1 已获取:: %s2 %s3', 'Item_Refunded': '%s1 已被退还:: %s2 %s3',
            'Item_GiftWrapped': '%s1 包装了礼物:: %s2 %s3', 'Item_PeriodicScoreReward': '%s1 赢得了： %s2 %s3',
            'Item_MvMBadgeCompletionReward': '%s1 获得了:: %s2 %s3', 'Item_MvMSquadSurplusReward': '%s1 获得了:: %s2 %s3',
            'Item_HolidayGift': '%s1 发现了一份假日礼物:: %s2 %s3', 'Item_RecipeOutput': '%s1 集齐了配方，获得了:: %s2 %s3',
            'Item_QuestOutput': '%s1 完成合同后获得了:: %s2 %s3', 'Item_TradeUp': '%s1 换购了:: %s2 %s3',
            'Item_QuestMerasmissionOutput': '%s1 完成马拉莫斯的任务后获得了::  %s2 %s3',
            'Item_ViralCompetitiveBetaPassSpread': '%s1 获得了:: %s2 %s3',
            'Item_CYOABloodMoneyPurchase': '%s1 花费血色奖券购买了:: %s2 %s3', 'Item_Painkit': '%s1 兑换了:: %s2 %s3',
            'TF_Weapon_Jar': '瓶罐式空手道', 'GameUI_ParticleHatUseHead': '调整特效位置',
            'TF_Spectator_CycleTargetFwd': '轮换目标（上一个）', 'TF_Spectator_CycleTargetRev': '轮换目标（下一个）',
            'TF_Tool_PaintCan_TeamColor2': '技工的工装服', 'TF_Tool_PaintCan_TeamColor3': '泡水的白大褂',
            'TF_Tool_PaintCan_TeamColor4': '巴拉克拉瓦万岁', 'TF_Tool_PaintCan_TeamColor5': '风度翩翩的格调',
            'TF_Tool_PaintCan_2': '泽老贪欲绿', 'TF_Tool_PaintCan_5': '坚定誓约紫', 'TF_Tool_PaintCan_1': '绝对经典绿',
            'TF_Tool_PaintCan_9': '老匠咖啡色', 'TF_Tool_PaintCan_16': '深沉石板青', 'TF_Tool_PaintCan_15': '极致闪亮粉',
            'TF_Tool_PaintCan_17': '平淡橄榄绿', 'TF_Tool_PaintCan_18': '苦涩青柠绿', 'TF_Tool_PaintCan_3': '贵族帽商紫',
            'TF_Tool_PaintCan_19': '商务米黄色', 'TF_Tool_PaintCan_10': '乡村尘土色', 'TF_Tool_PaintCan_20': '不公深橙红',
            'TF_Tool_PaintCan_21': '曼氏薄荷绿', 'TF_Tool_PaintCan_7': '猛男肌肉色', 'TF_Tool_PaintCan_11': '澳元素金色',
            'TF_Tool_PaintCan_22': '晚八点夜色', 'Tip_MvM_10_4': '小提示：在单波攻势中，收集齐所有掉落的现金，就会获得额外的现金奖励',
            'TF_MVM_COMPLETE_POP_FILE_DESC': '在一次任务中抵挡所有攻势。', 'TF_MVM_EARN_MONEY_BONUS_DESC': '在一波攻势结束时获得现金奖励。',
            'TF_MVM_DEFEND_CAP_DESC': '在同一波攻势中，防守舱门 10 次，以防止机器人投放炸弹。',
            'TF_MVM_COMPLETE_WAVE_WITHOUT_DYING_DESC': '在进阶难度下完成一波攻势而一次不死。',
            'TF_MVM_USE_BUILD_BOTTLE_DESC': '在同一波攻势中，在你原先的步哨枪被摧毁后的 3 秒内，使用水壶提供的“建筑瞬间升级”来建造一架新的步哨枪。',
            'TF_MVM_USE_AMMO_BOTTLE_DESC': '在同一波攻势中，使用水壶提供的“装填弹药”来为弹药耗尽的武器恢复弹药。',
            'TF_MVM_NO_ALARMS_IN_FINAL_WAVE_DESC': '在进阶难度任务下的最后一波攻势中，阻止炸弹抵达警戒区域。',
            'TF_MVM_MAPS_ROTTENBURG_BOMB_DESC': '在 Rottenburg 上以进阶难度完成一波攻势，并且没有让炸弹炸毁城镇。',
            'TF_MVM_MAPS_MANNHATTAN_STUN_RADIOWAVE_DESC': '在 Mannhattan 的一次进阶难度任务中，全队合计杀死 50 个正在接收信号的机器人。',
            'TF_PVE_Wave': '攻势', 'TF_PVE_WaveCount': '第 %s1 波攻势', 'TF_PVE_WaveCountFail': '第 %s1 波攻势失败',
            'TF_PVE_WaveComplete': '作战胜利！', 'TF_MVM_NoClassChangeAfterSetup': '只能在两波攻势之间更换兵种。',
            'Tip_MvM_10_1': '小提示：升级项将绑定至对应兵种或武器。首波攻势后不可退款', 'Tip_MvM_10_2': '小提示：在任务中，你需要大量地进行升级，才能抵挡敌人后期的攻势',
            'TF_ScoreBoard_GraphBuyBack': '每波攻势付费重生数', 'TF_ScoreBoard_GraphDeaths': '每波攻势阵亡次数',
            'TF_ScoreBoard_GraphCurrency': '每波攻势现金数', 'TF_ScoreBoard_Wave': '攻势', 'Winpanel_PVE_Evil_Wins': '作战失败',
            'TF_PVE_Player_UsedRecallBottle': '%player% 使用了快速回城水壶！',
            'TF_PVE_Player_UsedRefillAmmoBottle': '%player% 使用了弹药全满水壶！',
            'TF_PVE_Player_UsedBuildingUpgrade': '%player% 使用了建筑升级水壶！',
            'Attrib_CritBoost': '可消耗：获得爆击加成，持续 5 秒\\n（同时步哨射速翻倍）',
            'Attrib_Ubercharge': '可消耗：进入无敌状态，持续 5 秒\\n（同时步哨获得防御护盾）', 'Attrib_RefillAmmo': '可消耗：瞬间装满弹匣和后备弹药',
            'Attrib_BuildingInstaUpgrade': '可消耗：瞬间将所有建筑升级至满级', 'Attrib_ChargeMeterRateMult_shortdesc': '冷却速率 %s1%',
            'Attrib_ExplodeOnIgnite_shortdesc': '点燃汽油产生爆炸', 'Attrib_DmgTaken_From_Crit_Reduced_shortdesc': '爆击抗性 +%s1%',
            'Attrib_DmgTaken_From_Blast_Reduced_shortdesc': '爆炸抗性 +%s1%',
            'Attrib_DmgTaken_From_Bullets_Reduced_shortdesc': '子弹抗性 +%s1%',
            'Attrib_DamageForceReduction_shortdesc': '受击推力 %s1%', 'Attrib_Ubercharge_shortdesc': '进入无敌状态',
            'Attrib_ClipSize_Positive_shortdesc': '弹匣容量 +%s1%',
            'Attrib_MaxammoPrimary_Increased_shortdesc': '载弹量 +%s1%',
            'Attrib_MaxammoSecondary_Increased_shortdesc': '载弹量 +%s1%', 'Attrib_FastReload_shortdesc': '装填速度 +%s1%',
            'Attrib_DamageDone_Positive_shortdesc': '伤害 +%s1%', 'Attrib_MeleeRate_Positive_shortdesc': '挥舞速度 +%s1%',
            'Attrib_ProjectileSpeed_Increased_shortdesc': '炮弹速度 +%s1%',
            'Attrib_BleedingDuration_shortdesc': '目标流血 +%s1 秒', 'Attrib_CritBoost_OnKill_shortdesc': '杀敌后 +%s1 秒爆击效果',
            'Attrib_EffectBarRechargeRateIncreased_shortdesc': '冷却速率 +%s1%',
            'Attrib_BuildRateBonus_shortdesc': '建造速度 +%s1%',
            'Attrib_DispenserRadius_Increased_shortdesc': '补给器作用范围 +%s1%',
            'Attrib_MaxammoMetal_Increased_shortdesc': '金属持有量上限 +%s1%',
            'Attrib_EngyBuildingHealthBonus_shortdesc': '建筑物生命值 +%s1%',
            'Attrib_HealRate_Positive_shortdesc': '治疗速率 +%s1%',
            'Attrib_UberchargeRate_Positive_shortdesc': 'Ubercharge 充能速率 +%s1%',
            'Attrib_OverhealDecay_Positive_shortdesc': '超量治疗维持时间 +%s1%',
            'Attrib_UberDurationBonus_shortdesc': 'Ubercharge 持续时间 +%s1 秒',
            'Attrib_ShareConsumable_shortdesc': '共享增益效果', 'Attrib_AirBlastPushScale_shortdesc': '气爆推力 +%s1%',
            'Attrib_ChargeRechargeRateIncreased_shortdesc': '冲锋冷却速率 +%s1%', 'Attrib_MarkForDeath_shortdesc': '棒球标记目标',
            'Attrib_Rocket_Specialist': '每升级一次，火箭飞行速度和直接命中目标时的爆炸范围均 +15%。直接命中时，火箭伤害无视距离衰减，并附加击昏效果。',
            'Attrib_ExplodeOnIgnite': '点燃被汽油泼中的敌人会产生爆炸', 'Attrib_RageOnDamage': '通过造成伤害积攒怒气。怒气攒满后，按下“特殊攻击”键即可激活击退效果。',
            'Attrib_AttackProjectiles': '子弹可以击落飞行中的火箭和榴弹。每次升级提升精准度和击落频率。',
            'Attrib_ExplosiveSniperShot': '增加爆头产生爆炸的范围和对附近敌人造成的伤害',
            'Attrib_SentryFireRate_Increased_shortdesc': '步哨射速 +%s1%',
            'Attrib_SentryFireRate_Increased': '步哨枪射击速度 +%s1%',
            'Attrib_ShareConsumable': '在使用自己的增益水壶时，你的治疗对象也会获得同样的加成效果',
            'Attrib_Medic_MadMilkSyringes': '注射枪射出的针管内含高浓度的疯狂牛奶。多次命中可以叠加牛奶的作用时间，最多叠加到 4 秒。',
            'Attrib_RageOnHeal': '通过治疗队友积攒能量。充能完毕后，按下“特殊攻击”键即可部署正面能量护盾。',
            'TF_GET_CONSECUTIVEKILLS_NODEATHS_NAME': '大难不死', 'TF_PLAY_GAME_FRIENDSONLY_NAME': '有你们这些朋友...',
            'TF_WIN_GRAVELPIT_NOENEMYCAPS_NAME': '绝对防御', 'TF_KILL_CHARGING_DEMO_NAME': '急刹车',
            'TF_MEDIC_TOP_SCOREBOARD_NAME': '不得害人', 'TF_MEDIC_SIMUL_CHARGE_DESC': '与其他 2 名医生合作在同一时间部署 3 个 Ubercharge。',
            'TF_MEDIC_SETUP_CHARGE_NAME': '手术准备', 'TF_MEDIC_SETUP_CHARGE_DESC': '在准备阶段结束前将 Ubercharge 准备就绪。',
            'TF_MEDIC_RAPID_CHARGE_NAME': '创伤女王',
            'TF_MEDIC_RAPID_CHARGE_DESC': '在 5 分钟内部署 3 个 Ubercharge，并在该时间内辅助完成 5 次歼敌。',
            'TF_MEDIC_COUNTER_CHARGE_DESC': '在敌方医生开始部署 Ubercharge 的 8 秒内在附近部署你的 Ubercharge。',
            'TF_MEDIC_SAVE_TEAMMATE_NAME': '伤员分诊', 'TF_MEDIC_SAVE_TEAMMATE_DESC': '在队友被爆击的爆炸击中前一秒内给队友部署 Ubercharge。',
            'TF_MEDIC_CHARGE_BLOCKER_NAME': '预防医学', 'TF_MEDIC_CHARGE_BLOCKER_DESC': '使用 Ubercharge 帮助队友阻止敌人占领控制点。',
            'TF_MEDIC_SYRINGE_SCOUTS_NAME': '这样疼不疼？', 'TF_MEDIC_ASSIST_HEAVY_LONG_NAME': '龙头药企',
            'TF_MEDIC_ASSIST_SCOUT_NAME': '可能会有点刺痛', 'TF_MEDIC_ASSIST_SCOUT_DESC': '单次释放 Ubercharge 辅助一个侦察兵击杀 3 名敌人。',
            'TF_MEDIC_ASSIST_PYRO_NAME': '高压灭菌', 'TF_MEDIC_ASSIST_PYRO_DESC': '单次释放 Ubercharge 辅助一个火焰兵烧着 5 名敌人。',
            'TF_MEDIC_ASSIST_HEAVY_NAME': '钝击挫伤', 'TF_MEDIC_ASSIST_HEAVY_DESC': '单次释放 Ubercharge 辅助一个机枪手用拳头击打 2 名敌人。',
            'TF_MEDIC_ASSIST_DEMOMAN_NAME': '医学突破',
            'TF_MEDIC_ASSIST_DEMOMAN_DESC': '单次释放 Ubercharge 辅助一个爆破手摧毁 5 座敌方工程师建筑。',
            'TF_MEDIC_ASSIST_SOLDIER_DESC': '单次释放 Ubercharge 辅助一个士兵炸死 5 名敌人。', 'TF_MEDIC_HEAL_CALLERS_NAME': '医疗巡检',
            'TF_MEDIC_HEAL_CALLERS_DESC': '治疗 200 名呼叫过医生的队友', 'TF_MEDIC_EXTINGUISH_TEAMMATES_NAME': '药到火除',
            'TF_MEDIC_ASSIST_VS_NEMESES_NAME': '医生协助谋杀', 'TF_MEDIC_KILL_WHILE_CHARGED_NAME': '安慰剂效应',
            'TF_MEDIC_KILL_WHILE_CHARGED_DESC': '在 Ubercharge 准备就绪但未部署的情况下击杀 2 名敌人而不死。',
            'TF_MEDIC_BONESAW_NOMISSES_NAME': '骨科医生', 'TF_MEDIC_HEAL_HUGE_NAME': '专业医师',
            'TF_MEDIC_HEAL_GRIND_NAME': '外科主任', 'TF_MEDIC_CHARGE_JUGGLE_NAME': '第二诊断意见',
            'TF_MEDIC_CHARGE_JUGGLE_DESC': '一次性将 Ubercharge 部署给两个队友。', 'TF_MEDIC_CHARGE_FRIENDS_NAME': '家庭医疗',
            'TF_MEDIC_CHARGE_FRIENDS_DESC': '为你的 5 位 Steam 社区好友部署 Ubercharge。',
            'TF_MEDIC_INVITE_JOIN_CHARGE_DESC': '加入你的一位好友所在的比赛，并为其部署 Ubercharge。',
            'TF_MEDIC_HEAL_ACHIEVER_NAME': '临床关照', 'TF_PYRO_KILL_MULTIWEAPONS_NAME': '联合火力',
            'TF_PYRO_SIMULBURN_SCOUTS_NAME': '烤肠派对', 'TF_PYRO_FORCE_WATERJUMP_NAME': '战火洗礼',
            'TF_PYRO_KILL_POSTDEATH_NAME': '放任燃烧', 'TF_PYRO_KILL_CARRIERS_NAME': '烧毁假账',
            'TF_PYRO_REVEAL_SPIES_NAME': '意外起火', 'TF_PYRO_CAMP_POSITION_NAME': '蹲点烤火',
            'TF_PYRO_KILL_AXE_LARGE_NAME': '尽数伐除', 'TF_PYRO_KILL_FROM_BEHIND_NAME': '穷追猛烧',
            'TF_PYRO_BURN_SPIES_AS_YOU_NAME': '间谍猜猜看', 'TF_PYRO_BURN_SNIPERS_ZOOMED_NAME': '看火人',
            'TF_PYRO_BURN_MEDICS_CHARGED_NAME': '烧伤科病房',
            'TF_PYRO_BURN_MEDICS_CHARGED_DESC': '点燃 3 个预备部署 Ubercharge 的医生。',
            'TF_PYRO_REFLECT_PROJECTILES_NAME': '烫手山芋', 'TF_PYRO_KILL_HEAVIES_DESC': '用火焰喷射器杀死 50 个机枪手。',
            'TF_PYRO_KILL_UBERCHARGE_NAME': '烟火表演', 'TF_PYRO_KILL_UBERCHARGE_DESC': '在单次 Ubercharge 中杀死 3 名敌人。',
            'TF_PYRO_DEFEND_POINTS_NAME': '可控焚烧', 'TF_PYRO_KILL_GRIND_NAME': '灭火英雄',
            'TF_PYRO_BURN_MEDICPAIR_NAME': '新火种', 'TF_PYRO_KILL_TEAMWORK_NAME': '二度烧伤',
            'TF_PYRO_BURN_SPY_TAUNT_NAME': '借个火？', 'TF_PYRO_DOMINATE_LEAVESVR_NAME': '退服烧烤',
            'TF_PYRO_REFLECT_CROCKET_KILL_NAME': '反弹大师', 'TF_PYRO_KILL_TAUNTERS_NAME': '起舞自焚',
            'TF_PYRO_DOUBLE_KO_NAME': '玉石俱焚', 'TF_PYRO_FREEZECAM_TAUNTS_NAME': '冷嘲热讽',
            'TF_PYRO_KILL_GRIND_LARGE_NAME': '消防队长', 'TF_PYRO_IGNITE_FLAREGUN_NAME': '灼人眼球',
            'TF_PYRO_IGNITE_WITH_RAINBOW_DESC': '使用彩虹喷灯的嘲讽攻击点燃 3 名敌人。', 'TF_HEAVY_ASSIST_MEDIC_LARGE_NAME': '劳动分工',
            'TF_HEAVY_EARN_MEDIC_DOMINATION_NAME': '红色十月节', 'TF_HEAVY_BLOCK_INVULN_HEAVY_NAME': '苏维埃集团',
            'TF_HEAVY_RECEIVE_UBER_GRIND_DESC': '获得 50 次 Ubercharge。', 'TF_HEAVY_ASSIST_HEAVY_GRIND_NAME': '苏维埃联盟',
            'TF_HEAVY_CLEAR_STICKYBOMBS_NAME': '掌控生产资料', 'TF_HEAVY_TAKE_MULTI_DAMAGE_NAME': '拉斯普京',
            'TF_HEAVY_KILL_DOMINATED_NAME': '锦上添花', 'TF_HEAVY_SURVIVE_CROCKET_NAME': '坏我好事',
            'TF_HEAVY_ASSIST_GRIND_NAME': '集体化', 'TF_HEAVY_HEAL_MEDIKITS_NAME': '生命值再分配',
            'TF_HEAVY_KILL_SHOTGUN_NAME': '定量配给', 'TF_HEAVY_FIRST_TO_CAP_NAME': '先锋党员',
            'TF_HEAVY_DEFEND_CONTROL_POINT_NAME': '高尔基的车位', 'TF_HEAVY_KILL_CAPPING_ENEMIES_NAME': '肃清',
            'TF_HEAVY_FREEZECAM_TAUNT_NAME': '改革前夕', 'TF_HEAVY_EAT_SANDWICHES_NAME': '暴饮暴食',
            'TF_HEAVY_KILL_SCOUTS_NAME': '别动我三明治', 'TF_SCOUT_FIRST_BLOOD_KILL_NAME': '第一滴血，第二部',
            'TF_SCOUT_WELL_EARLY_KILL_NAME': '光速下场', 'TF_SCOUT_DESTROY_TELEPORTERS_NAME': '收尾',
            'TF_SCOUT_DESTROY_SENTRY_WITH_PISTOL_NAME': '阻杀', 'TF_SCOUT_DOUBLE_JUMPS_NAME': '击球手上场',
            'TF_SCOUT_ASSIST_MEDIC_DESC': '借助医生的 Ubercharge 杀死 3 个敌人。',
            'TF_SCOUT_KILL_CHARGED_MEDICS_DESC': '杀死 1 个预备部署 Ubercharge 的医生。', 'TF_SCOUT_FLAG_CAP_GRIND_NAME': '绕场全垒打',
            'TF_SCOUT_DODGE_DAMAGE_NAME': '狡猾闪躲', 'TF_SCOUT_KNOCK_INTO_TRAIN_NAME': '秋季经典',
            'TF_SCOUT_STUN_INTO_TRAIN_NAME': '界外区', 'TF_SCOUT_STUN_INTO_TRAIN_DESC': '通过击昏或减速敌人来使其死于环境伤害。',
            'TF_SCOUT_STUN_UBER_ENEMIES_DESC': '击昏 2 个预备部署 Ubercharge 的医生。',
            'TF_SCOUT_STUN_CAPPING_ENEMIES_NAME': '近身球', 'TF_SCOUT_MAX_STUNS_NAME': '超高远全垒打',
            'TF_SCOUT_KILL_FROM_BEHIND_NAME': '愣神触杀', 'TF_SCOUT_CAPTURE_THREE_POINTS_NAME': '三连击败',
            'TF_SCOUT_START_AND_FINISH_CAP_NAME': '局势大开', 'TF_SCOUT_BACKSCATTER_KILL_SPY_GRIND_NAME': '反背刺',
            'TF_SNIPER_JARATE_DOMINATED_NAME': '落汤鸡', 'TF_SNIPER_CAPTURE_FLAG_NAME': '计划周全',
            'TF_SNIPER_KILL_INVIS_SPY_DESC': '一击杀死一名完全隐身的间谍', 'TF_SNIPER_KILL_MIDAIR_SCOUT_NAME': '骤死',
            'TF_SNIPER_KILL_SPIES_MELEE_NAME': '砍杀幽灵',
            'TF_SNIPER_KILL_CHARGED_MEDIC_DESC': '杀死 1 个预备部署 Ubercharge 的医生。', 'TF_SNIPER_KILL_FAILED_SPY_NAME': '休克疗法',
            'TF_SNIPER_JARATE_MEDIC_PAIR_NAME': '泼冷水', 'TF_SNIPER_JARATE_ASSISTS_NAME': '一急助攻',
            'TF_SPY_FREEZECAM_FLICK_NAME': '独家丑闻', 'TF_SPY_BACKSTAB_ENGY_SAP_BUILDING_NAME': '烂枪客',
            'TF_SPY_SAP_BUILDING_BACKSTAB_ENGY_NAME': '敲骨吸髓', 'TF_SPY_BACKSTAB_MEDIC_PAIR_NAME': '我能插手一下吗？',
            'TF_SPY_BACKSTAB_FRIENDS_NAME': '友尽间谍', 'TF_SPY_BREAK_SHIELD_KILL_SNIPER_NAME': '换个死法',
            'TF_SPY_KILL_WORKING_ENGY_NAME': '施工中断', 'TF_SPY_FAST_CAP_NAME': '女王密探',
            'TF_SPY_BACKSTAB_DOMINATING_ENEMY_NAME': '高价值目标', 'TF_SPY_REVENGE_WITH_BACKSTAB_NAME': '卷土重来',
            'TF_SPY_KNIFE_KILL_WHILE_JARATED_NAME': '雨中暗杀', 'TF_SPY_BACKSTAB_GRIND_NAME': '间谍大师',
            'TF_SPY_SAPPER_GRIND_NAME': '破坏专家', 'TF_SPY_SAPPER_TEAMWORK_DESC': '在队友瘫痪敌人一支步哨枪后的 3 秒内, 瘫痪敌人的另一支步哨枪',
            'TF_SPY_BACKSTAB_MEDIC_CHARGED_DESC': '背刺 1 个预备部署 Ubercharge 的医生。',
            'TF_SPY_BACKSTAB_ENEMY_SWITCH_PYRO_NAME': '刺杀转世', 'TF_SPY_FEIGN_DEATH_KILL_NAME': '潜伏特工',
            'TF_SPY_KILL_BACKSCATTER_SCOUT_NAME': '眼疾手快', 'TF_HALLOWEEN_COLLECT_PUMPKINS_NAME': '糖果验尸官',
            'TF_HALLOWEEN_DOMINATE_FOR_HAT_NAME': '夺取可怕的折叠礼帽', 'TF_HALLOWEEN_PUMPKIN_KILL_NAME': '打爆南瓜',
            'TF_HALLOWEEN_BOSS_KILL_NAME': '沉睡谷之殇', 'TF_HALLOWEEN_CRAFT_SAXTON_MASK_NAME': '萨克斯袋.霍尔',
            'TF_HALLOWEEN_EYEBOSS_KILL_NAME': '致盲', 'TF_HALLOWEEN_HELLTOWER_RARE_SPELL_DESC': '找到并施放一个稀有魔咒',
            'TF_SOLDIER_KILL_TAUNT_DESC': '使用手雷炸死一名敌人。', 'TF_SOLDIER_KILL_ENGY_NAME': '乱世工魂',
            'TF_SOLDIER_DESTROY_STICKIES_NAME': '拆弹新兵', 'TF_SOLDIER_KILL_DEFENSELESS_DESC': '在一局结束后，杀死 3 名手无寸铁的玩家。',
            'TF_SOLDIER_KILL_ON_FIRE_NAME': '赴汤蹈火', 'TF_SOLDIER_RJ_EQUALIZER_KILL_NAME': '使命必达',
            'TF_SOLDIER_BUFF_TEAMMATES_NAME': '助威男孩', 'TF_SOLDIER_KILL_PYRO_NAME': '故技重施',
            'TF_SOLDIER_ASSIST_MEDIC_UBER_DESC': '辅助 1 个医生在单次 Ubercharge 中炸死 5 名敌人。',
            'TF_SOLDIER_PARACHUTE_KILL_GROUP_NAME': '居高临下', 'TF_SOLDIER_PARACHUTE_KILL_PARACHUTE_NAME': '空中缠斗',
            'TF_SOLDIER_AIRSTRIKE_GROUP_KILL_NAME': '投弹轰炸！',
            'TF_DEMOMAN_DESTROY_BUILDINGS_WITH_MEDIC_DESC': '在医生发动的单次 Ubercharge 中摧毁 5 座敌方工程师建筑。',
            'TF_DEMOMAN_DECAPITATE_PLAYERS_NAME': '摸不着头脑', 'TF_DEMOMAN_DECAPITATE_NEMESIS_NAME': '你死我活',
            'TF_DEMOMAN_KILL_X_CAPPING_ONEDET_NAME': '苏格兰卫队', 'TF_DEMOMAN_FREEZECAM_RUMP_DESC': '送敌方玩家一张你扭屁股的定格照。',
            'TF_DEMOMAN_DESTROY_X_STICKYBOMBS_NAME': '皇家劫案', 'TF_DEMOMAN_KILL3_WITH_PIPE_SETUPS_NAME': '炸药作响',
            'TF_DEMOMAN_QUICK_KILLS_NAME': '连锁反应', 'TF_DEMOMAN_CHARGE_KILL_CHARGING_DEMO_NAME': '迎头冲锋',
            'TF_ENGINEER_REVENGE_CRIT_SENTRY_KILLER_NAME': '曲线复仇', 'TF_ENGINEER_KILL_SPY_TWO_SAPPERS_NAME': '手脚麻利',
            'TF_ENGINEER_KILL_DISGUISED_SPY_NAME': '扳手法网', 'TF_ENGINEER_DESTROY_SAPPERS_NAME': '工兵遍地',
            'TF_ENGINEER_SENTRY_KILL_LIFETIME_GRIND_NAME': '德州头号屠宰场', 'TF_ENGINEER_FREEZECAM_SENTRY_NAME': '土墓工程',
            'TF_ENGINEER_DISPENSER_HEAL_GROUP_NAME': '医生休假', 'TF_ENGINEER_TAUNT_KILL_NAME': '吉他暴击',
            'TF_ENGINEER_KILL_ASSIST_NAME': '工作代理', 'TF_ENGINEER_DISPENSER_HEAL_GRIND_NAME': '药房牛仔',
            'TF_ENGINEER_REPAIR_TEAM_GRIND_NAME': '共同御敌', 'TF_ENGINEER_TANK_DAMAGE_NAME': '经久耐用',
            'TF_ENGINEER_HEAVY_ASSIST_NAME': '自古英雄不寂寞', 'TF_REPLAY_SAVE_REPLAY_NAME': '杀青',
            'TF_MAPS_FOUNDRY_WIN_ROUNDS_NAME': '百炼成钢', 'TF_MAPS_FOUNDRY_TELEPORT_AND_CAP_NAME': '非法占领',
            'TF_MAPS_FOUNDRY_PUSH_INTO_CAULDRON_NAME': '再见，终结者', 'TF_MAPS_FOUNDRY_PLAY_EACH_CLASS_NAME': '全职杀手',
            'TF_MVM_ADVANCED_EARN_ALL_BONUSES_NAME': '战争横财', 'TF_MVM_PLAY_EACH_CLASS_NAME': '万金油黑客',
            'TF_MVM_DESTROY_TANK_WHILE_DEPLOYING_NAME': '千钧一发', 'TF_MVM_DEFEND_CAP_NAME': '拦截垃圾邮件',
            'TF_MVM_KILL_BOMB_CARRIERS_NAME': '执刑程序', 'TF_MVM_COMPLETE_WAVE_WITHOUT_DYING_NAME': '机械降神',
            'TF_MVM_COMPLETE_TOUR_NAME': '奇袭阵列', 'TF_MVM_USE_UBER_BOTTLE_NAME': '德国工艺',
            'TF_MVM_USE_UBER_BOTTLE_DESC': '使用水壶提供的“ Ubercharge ”摧毁 15 个机器人', 'TF_MVM_USE_BUILD_BOTTLE_NAME': '撤销删除',
            'TF_MVM_MAX_PLAYER_RESISTANCES_NAME': '极致性能', 'TF_MVM_KILL_SENTRY_BUSTER_NAME': '手动关停',
            'TF_MVM_SOLDIER_BUFF_TEAM_NAME': '涡轮增压', 'TF_MVM_DEMO_GROUP_KILL_NAME': '技术破坏',
            'TF_MVM_SCOUT_MARK_FOR_DEATH_NAME': '机器人也会做梦吗？', 'TF_MVM_PYRO_BOMB_RESET_NAME': '硬重启',
            'TF_MVM_MAPS_ROTTENBURG_BOMB_NAME': '固若金汤', 'TF_MVM_MAPS_MANNHATTAN_PIT_NAME': '诱敌深入',
            'TF_MVM_MAPS_MANNHATTAN_MYSTERY_NAME': '现可合法食用', 'TF_MVM_MAPS_MANNHATTAN_BOMB_BOT_GRIND_NAME': '都市突击',
            'TF_MVM_SENTRY_BUSTER_FRIENDLY_FIRE_DESC': '引爆步哨毁灭者，利用其产生的爆炸一次干掉 5 个机器人。',
            'TF_MVM_SNIPER_COLLECT_HEADSHOT_MONEY_NAME': '稳赚不亏', 'TF_MVM_MEDIC_REVIVE_TEAMMATES_NAME': '双重复活',
            'TF_MVM_MEDIC_REVIVE_TEAMMATES_DESC': '在 5 秒内使用单次 Ubercharge 快速复活 2 名队友。',
            'TF_MVM_ROCKET_SPECIALIST_KILL_GRIND_NAME': '一箭五雕', 'TF_MAPS_DOOMSDAY_SOLO_CAPTURE_NAME': '任务控制中心',
            'TF_MAPS_DOOMSDAY_PLAY_GAME_FRIENDS_DESC': '与 5 个或以上的好友一同游戏。', 'TF_MAPS_DOOMSDAY_WIN_ROUNDS_NAME': '太空先锋',
            'TF_MAPS_DOOMSDAY_PLAY_EACH_CLASS_NAME': '九号计划',
            'TF_MAPS_DOOMSDAY_KILL_CARRIERS_DESC': '一局内杀死 6 名携带澳洲晶矿元素的敌人。',
            'TF_MAPS_DOOMSDAY_RIDE_THE_ELEVATOR_NAME': '远地占点',
            'TF_MAPS_DOOMSDAY_PUSH_INTO_EXHAUST_DESC': '在回合结束时将一名玩家推入火箭的排气渠道中。',
            'TF_MAPS_DOOMSDAY_DEFEND_CARRIER_NAME': '逃逸险境', 'TF_MAPS_STANDIN_WIN_ROUNDS_NAME': '屹立不倒',
            'TF_MAPS_PROCESS_WIN_ROUNDS_NAME': '优胜劣汰',
            'TF_MAPS_SNAKEWATER_KILL_ENEMIES_IN_MIDDLE_DESC': '在中央控制点上方的平台和圆木上消灭 15 个敌人。',
            'TF_MAPS_POWERHOUSE_PUSH_BACK_AND_WIN_NAME': '力挽狂澜', 'TF_MAPS_POWERHOUSE_FAST_FINAL_CAP_NAME': '马不停蹄',
            'TF_TEAM_PYROVISION_NAME': '群体性歇斯底里', 'TF_WIN_2FORT_NOENEMYCAPS_DESC': '在 2Fort 上完胜。',
            'TF_WIN_WELL_MINIMUMTIME_DESC': '在 Well 上于 5 分钟或更短时间内赢下一局。',
            'TF_WIN_HYDRO_NOENEMYCAPS_DESC': '在 Hydro 上未丧失任何控制点并赢下一局。',
            'TF_WIN_DUSTBOWL_NOENEMYCAPS_DESC': '在 Dustbowl 上未丧失任何控制点并成功守住。',
            'TF_WIN_GRAVELPIT_NOENEMYCAPS_DESC': '在 Gravel Pit 上未丧失任何控制点并成功守住。',
            'TF_PLAY_GAME_EVERYMAP_DESC': '在2Fort、Dustbowl、Granary、Gravel Pit、Hydro 和 Well（控制点）上完整游玩一局。',
            'TF_HALLOWEEN_COLLECT_GOODY_BAG_DESC': '在 Mann Manor 中收集一个摄魂石像鬼。',
            'TF_HALLOWEEN_HELLTOWER_RARE_SPELL_NAME': 'Helltower：地狱魔咒',
            'TF_HALLOWEEN_HELLTOWER_WIN_ROUNDS_NAME': 'Helltower：竞技之魂',
            'TF_HALLOWEEN_HELLTOWER_ENVIRONMENTAL_KILLS_NAME': 'Helltower：心理博弈',
            'TF_HALLOWEEN_HELLTOWER_SKELETON_GRIND_NAME': 'Helltower：骷髅政变',
            'TF_HALLOWEEN_HELLTOWER_KILL_GRIND_NAME': 'Helltower：魔咒狂欢',
            'TF_HALLOWEEN_HELLTOWER_KILL_BROTHERS_NAME': 'Helltower：无尽折磨',
            'TF_HALLOWEEN_HELLTOWER_MILESTONE_NAME': 'Helltower：离奇之 4',
            'TF_HALLOWEEN_HELLTOWER_MILESTONE_DESC': '获得 4 项 Helltower 成就',
            'TF_HALLOWEEN_HELLTOWER_SKULL_ISLAND_REWARD_NAME': 'Helltower：逃离火海',
            'TF_HALLOWEEN_DOOMSDAY_KILL_KARTS_NAME': 'Carnival of Carnage：碰碰大丰收',
            'TF_HALLOWEEN_DOOMSDAY_COLLECT_DUCKS_NAME': 'Carnival of Carnage：鸭力山大',
            'TF_HALLOWEEN_DOOMSDAY_SCORE_GOALS_NAME': 'Carnival of Carnage：帽子戏法',
            'TF_HALLOWEEN_DOOMSDAY_RESPAWN_TEAMMATES_NAME': 'Carnival of Carnage：轮下转世',
            'TF_HALLOWEEN_DOOMSDAY_TINY_SMASHER_NAME': 'Carnival of Carnage：军备裁减',
            'TF_HALLOWEEN_DOOMSDAY_WIN_MINIGAMES_NAME': 'Carnival of Carnage：碰，碰，碰',
            'TF_HALLOWEEN_DOOMSDAY_MILESTONE_NAME': 'Carnival of Carnage：好戏登场',
            'TF_HALLOWEEN_DOOMSDAY_MILESTONE_DESC': '完成 4 项 Carnival of Carnage 成就。',
            'TF_MVM_MAPS_MANNHATTAN_PIT_DESC': '在 Mannhattan 的单波攻势中，全队合计让 10 个机器人掉入陷阱。',
            'TF_MVM_MAPS_MANNHATTAN_MYSTERY_DESC': '在 Mannhattan 的某处：啊…疼…啊…！',
            'TF_MAPS_SNAKEWATER_WIN_ROUNDS_NAME': 'Snakewater 推销员',
            'TF_MVM_HEAVY_RAGE_PUSH_DEPLOYING_ROBOT_DESC': '作为机枪手，在单波攻势中使用怒气击退效果推开一个即将投放炸弹的机器人。',
            'TF_MVM_USE_TELEPORT_BOTTLE_DESC': '使用水壶提供的“传送至重生点”效果在 5 秒内杀死一个炸弹运送者。',
            'TF_MVM_KILL_MEDICS_CHARGED_DESC': '在一波攻势中击杀 5 个预备部署 Ubercharge 的医生。',
            'TF_MVM_KILL_BOMB_CARRIERS_DESC': '在同一波攻势中，连续摧毁 15 个还没升级的运送炸弹的机器人。',
            'TF_MVM_SOLDIER_BUFF_TEAM_DESC': '用士兵在单波攻势内同时对 4 名队友释放战旗加成。',
            'TF_MVM_MEDIC_SHARE_BOTTLES_DESC': '作为医生，在单波攻势内分享水壶效果 5 次。',
            'TF_MVM_SCOUT_MARK_FOR_DEATH_DESC': '在单波攻势内，用侦察兵的睡魔棒球为 15 个机器人打上死亡标记。',
            'TF_MVM_PYRO_BOMB_RESET_DESC': '用火焰兵在单波攻势中销毁炸弹 3 次。'}


def main():
    # 读取文件
    loc_file = Path(loc_file_input)
    output_file = Path(loc_file_output)
    # 记录集
    matched_keys = set()

    # 正则表达式：
    # group 1 = 空格或制表符（缩进）- (\s*)
    # group 2 = key - ([^"\n]+)
    # group 3 = text - ([^"\n]*)
    # group 4 = 后续文本，如注释 - (.*)
    pattern = re.compile(r'^\s*"([^"\n]+)"\s+"([^"\n]*)"(?:\s*//.*)?$', re.MULTILINE)

    # 从原文件读取内容
    with loc_file.open(encoding="utf-16") as file:
        content = file.read()
        output = content

    # 基于字典，处理对读取的文本
    for match in pattern.finditer(content):
        key, value = match.groups()

        if key in loc_dict:
            old_entry = match.group(0)
            new_entry = old_entry.replace(f'"{value}"', f'"{loc_dict[key]}"')
            # 执行替换
            output = output.replace(old_entry, new_entry)
            # 记录该key已替换
            matched_keys.add(key)

    # 将处理后的文本输出为文件
    with output_file.open("w", encoding="utf-16") as file:
        file.write(output)

    # 处理未匹配词条
    unmatched_keys = set(loc_dict.keys()) - matched_keys

    # 打印反馈表
    print(f"替换完成，已写入文件：{output_file.name}")
    print(f"成功匹配替换 {len(matched_keys)} 项")
    print(f"未匹配 {len(unmatched_keys)} 项：")
    for key in sorted(unmatched_keys):
        print(f" - {key}")


if __name__ == "__main__":
    main()
